### ISSUE TITLE
Problem when using getsuppliers

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#1043]
I don't know whether I am hitting a limit but when I'm using CGRates/Opensips native and throwing about 50-100cps I get;

I'm calling getsuppliers every call to get the supplier list.

fatal error: sync: unlock of unlocked mutex

goroutine 28291 [running]:
runtime.throw(0x102fc84, 0x1e)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420569598 sp=0xc420569578
sync.throw(0x102fc84, 0x1e)
        /usr/local/go/src/runtime/panic.go:585 +0x35 fp=0xc4205695b8 sp=0xc420569598
sync.(*Mutex).Unlock(0xc4208f9c18)
        /usr/local/go/src/sync/mutex.go:113 +0xa4 fp=0xc4205695e0 sp=0xc4205695b8
github.com/cgrates/cgrates/guardian.(*itemLock).unlock(0xc4208f9c00)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:51 +0x49 fp=0xc420569608 sp=0xc4205695e0
github.com/cgrates/cgrates/guardian.(*GuardianLock).unlockItems(0x15d5ce0, 0xc4209b2288, 0x1, 0x1)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:84 +0x44 fp=0xc420569630 sp=0xc420569608
github.com/cgrates/cgrates/guardian.(*GuardianLock).UnguardIDs(0x15d5ce0, 0xc4208a7ff0, 0x1, 0x1)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:142 +0x1ea fp=0xc4205696c0 sp=0xc420569630
github.com/cgrates/cgrates/engine.(*SupplierService).matchingSupplierProfilesForEvent(0xc4200700c0, 0xc4209ab8c0, 0xc4209b2280, 0x1, 0x1, 0x0, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/suppliers.go:154 +0x513 fp=0xc420569950 sp=0xc4205696c0
github.com/cgrates/cgrates/engine.(*SupplierService).sortedSuppliersForEvent(0xc4200700c0, 0xc4209ab8c0, 0xc42052ca60, 0x2, 0x2)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/suppliers.go:268 +0x4f fp=0xc420569a10 sp=0xc420569950
github.com/cgrates/cgrates/engine.(*SupplierService).V1GetSuppliers(0xc4200700c0, 0xc4209ab8c0, 0xc42015b2c0, 0xc42037ad30, 0x191)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/suppliers.go:313 +0xb1 fp=0xc420569a90 sp=0xc420569a10
github.com/cgrates/cgrates/apier/v1.(*SupplierSv1).GetSuppliers(0xc42000e008, 0xc4209ab8c0, 0xc42015b2c0, 0x0, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/suppliers.go:87 +0x42 fp=0xc420569ac8 sp=0xc420569a90
runtime.call64(0xc42054e480, 0xc42000e040, 0xc420ea42a0, 0x1800000028)
        /usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc420569b18 sp=0xc420569ac8
reflect.Value.call(0xc420070120, 0xc42000e040, 0x13, 0x10133dd, 0x4, 0xc42052cf20, 0x3, 0x3, 0x3, 0x30, ...)
        /usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc420569e60 sp=0xc420569b18
reflect.Value.Call(0xc420070120, 0xc42000e040, 0x13, 0xc420ce3720, 0x3, 0x3, 0xc4209ab800, 0xc4208a6601, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420569ec8 sp=0xc420569e60
net/rpc.(*service).call(0xc42054a080, 0xc42012a0c0, 0xc42040d9b0, 0xc420076200, 0xc420158180, 0xf65360, 0xc4209ab8c0, 0x16, 0xf10ba0, 0xc42015b2c0, ...)
        /usr/local/go/src/net/rpc/server.go:387 +0x144 fp=0xc420569f78 sp=0xc420569ec8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420569f80 sp=0xc420569f78
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:481 +0x404

goroutine 1 [chan receive, 1 minutes]:
main.main()
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:1001 +0xe95

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

**Comment by DigiDaz** [comment]
I've added a zip of the strace.
[cgrates.zip](https://github.com/cgrates/cgrates/files/1858179/cgrates.zip)

**Comment by danbogos** [comment]
hey @DigiDaz 

Thanks for your report. It looks like a valid bug to me. Will check it and come back to you.

DanB

**Comment by arsperger** [comment]
Hi guys,

In my tests limit is about 10 cps

I am getting errors:

`<FreeSWITCHAgent> Could not authorize event 20f33250-7657-4027-b8d9-d6d39965a656, error: SUPPLIERS_ERROR:unexpected EOF`

and on the RALS component side:

```
21:33:06  cgr-engine[30148]: panic: sync: unlock of unlocked mutex 
 21:33:06  cgr-engine[30148]: goroutine 774 [running]:
 21:33:06  cgr-engine[30148]: sync.(*Mutex).Unlock(0xc420586f38)
 21:33:06  cgr-engine[30148]: /usr/local/go/src/sync/mutex.go:184 +0xc1 
 21:33:06  cgr-engine[30148]: github.com/cgrates/cgrates/guardian.(*itemLock).unlock(0xc420586f20)
 21:33:06  systemd[1]: cgrates.service: main process exited, code=exited, status=2/INVALIDARGUMENT
 21:33:06  rsyslogd-2007: action 'action 17' suspended, next retry is Wed  21:33:36 2018 [try http://www.rsyslog.com/e/2007 ]
 21:33:06  systemd[1]: Unit cgrates.service entered failed state.
 21:33:06  cgr-engine[30148]: /root/go/src/github.com/cgrates/cgrates/guardian/guardian.go:51 +0x49 
 21:33:06  cgr-engine[30148]: github.com/cgrates/cgrates/guardian.(*GuardianLock).unlockItems(0x15e10e0, 0xc420691800, 0xa7, 0x100)
 21:33:06  cgr-engine[30148]: /root/go/src/github.com/cgrates/cgrates/guardian/guardian.go:84 +0x3c 
 21:33:06  cgr-engine[30148]: github.com/cgrates/cgrates/guardian.(*GuardianLock).UnguardIDs(0x15e10e0, 0xc420558000, 0xa7, 0xa7) 
 21:33:06  cgr-engine[30148]: /root/go/src/github.com/cgrates/cgrates/guardian/guardian.go:142 +0x204
 21:33:06  cgr-engine[30148]: github.com/cgrates/cgrates/guardian.(*GuardianLock).GuardIDs.func1(0x15e10e0, 0x12a05f200, 0xc420558000, 0xa7, 0xa7) 
 21:33:06  cgr-engine[30148]: /root/go/src/github.com/cgrates/cgrates/guardian/guardian.go:124 +0x57 
 21:33:06  cgr-engine[30148]: created by github.com/cgrates/cgrates/guardian.(*GuardianLock).GuardIDs
 21:33:06  cgr-engine[30148]: /root/go/src/github.com/cgrates/cgrates/guardian/guardian.go:122 +0xa6 
 21:33:07  systemd[1]: cgrates.service holdoff time over, scheduling restart.
 21:33:07  systemd[1]: Stopping Control CGRateS - carrier grade real-time charging system...
 21:33:07  systemd[1]: Starting Control CGRateS - carrier grade real-time charging system...
 21:33:07  systemd[1]: Started Control CGRateS - carrier grade real-time charging system.

```

CGRateS 0.9.1~rc8 git+e48319c (2018-04-27T15:44:41+02:00)

Let me know if you need more debug info  

Thanks
Arsen

**Comment by danbogos** [comment]
hey @arsperger 

Can you please recompile cgrates with -race flag and post here the races detected?

Ta,
DanB

**Comment by arsperger** [comment]
Hi Dan,

Thanks for your quick response. 
Here is a log with -race flag enabled

[cgrates_cps_issue.txt](https://github.com/cgrates/cgrates/files/1967815/cgrates_cps_issue.txt)

**Comment by arsperger** [comment]
Dan,

We have CDRs export in real-time via ampq and I have noticed that if I disable it, cgrates doesn't produce races. I also use remote mongo host for DataDB, I have replaced it with a local redis but it did not help much.

**Comment by danbogos** [comment]
hi @arsperger 

Sorry for the delay, was out for OpenSIPS Summit.
Have just checked the log you provided and it appears that the data race (which is different from the suppliers panic we have here) is produced by export/store. Will address it separately, while working on the new derive chargers. To be notified when fixed, please open a new issue related to that.
Regarding suppliers, I have identified the issue but need to investigate further for the cause since that part of the code looked OK before.
Will come back here.

DanB

**Comment by danbogos** [comment]
hey @DigiDaz, @arsperger 

I have just pushed a fix. Please retest with full speed (could be we hit some other concurrency but hopefully no unlock issues.

DanB

PS: I am also rebuilding .deb packages

**Comment by danbogos** [comment]
hey guys,

This issue should be nailed for good. We have redesigned the guardian (component which does global locks) and it should not longer have concurrency issues.

Please retest using today's master (I have also rebuilt the temporary package), and report back if any issues.

Thanks for your efforts!

DanB

**Comment by DigiDaz** [comment]
I have been testing today with 100cps and have had no problems so looks like the issue is solved. Thanks!
