### ISSUE TITLE
Panic on StatS - concurrent map read/write

### ISSUE THREAD

**Issue by alexsosic** [cgrates/cgrates#1067]
While doing some stress test on our infrastructure, 50 to 100 concurrent calls, RAL crashes with this log:
```
fatal error: concurrent map read and map write
goroutine 47 [running]:
runtime.throw(0x1031cc4, 0x21)
    /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420b8f6a8 sp=0xc420b8f688
runtime.mapaccess2(0xec5bc0, 0xc420616120, 0xc42055c980, 0x86, 0xc4218f2128)
    /usr/local/go/src/runtime/hashmap.go:377 +0x244 fp=0xc420b8f6f0
sp=0xc420b8f6a8
reflect.mapaccess(0xec5bc0, 0xc420616120, 0xc42055c980, 0xc420616120)
    /usr/local/go/src/runtime/hashmap.go:1128 +0x3f fp=0xc420b8f728
sp=0xc420b8f6f0
reflect.Value.MapIndex(0xec5bc0, 0xc420616160, 0x195, 0xe71ba0,
0xc42055c980, 0x98, 0xf0f520, 0xc42082d998, 0x86)
    /usr/local/go/src/reflect/value.go:1058 +0x128 fp=0xc420b8f7b0
sp=0xc420b8f728
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*encFnInfo).kMap(0xc420e71088,
0xec5bc0, 0xc420616160, 0x195)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:694
+0x51c fp=0xc420b8f8c0 sp=0xc420b8f7b0
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*Encoder).doEncodeValue(0xc42020ea00,
0xec5bc0, 0xc420616160, 0x195, 0x0, 0x0, 0x101)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:1203
+0x6d fp=0xc420b8f928 sp=0xc420b8f8c0
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc42020ea00,
0xec5bc0, 0xc420616160, 0x195, 0x0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:1218
+0xa7 fp=0xc420b8f980 sp=0xc420b8f928
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*encFnInfo).kStruct(0xc420e71008,
0xf5d540, 0xc420616150, 0x199)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:576
+0x723 fp=0xc420b8fac0 sp=0xc420b8f980
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*Encoder).doEncodeValue(0xc42020ea00,
0xf5d540, 0xc420616150, 0x199, 0x0, 0x0, 0x100)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:1203
+0x6d fp=0xc420b8fb28 sp=0xc420b8fac0
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*Encoder).encodeI(0xc42020ea00,
0xf552e0, 0xc420616150, 0x100)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:1211
+0xc9 fp=0xc420b8fb80 sp=0xc420b8fb28
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*Encoder).encode(0xc42020ea00,
0xf552e0, 0xc420616150)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:1147
+0x157 fp=0xc420b8fbc8 sp=0xc420b8fb80
github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec.(*Encoder).Encode(0xc42020ea00,
0xf552e0, 0xc420616150, 0x0, 0x0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/ugorji/go/codec/encode.go:1039
+0x84 fp=0xc420b8fbf0 sp=0xc420b8fbc8
github.com/cgrates/cgrates/engine.(*CodecMsgpackMarshaler).Marshal(0xc42037a090,
0xf552e0, 0xc420616150, 0xc4204ac128, 0xc4206160c0, 0xc4204ac120,
0x15b9c70, 0x0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/storage_interface.go:297
+0x96 fp=0xc420b8fc30 sp=0xc420b8fbf0
github.com/cgrates/cgrates/engine.(*StatTCD).Marshal(0xc420616150,
0x14fbde0, 0xc42037a090, 0xc42140e088, 0x2b702, 0x310c0, 0x0, 0x0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/statmetrics.go:316
+0x47 fp=0xc420b8fc80 sp=0xc420b8fc30
github.com/cgrates/cgrates/engine.NewStoredStatQueue(0xc4203093e0,
0x14fbde0, 0xc42037a090, 0x42ba4f, 0x1081270, 0xc4219ece08)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/libstats.go:64
+0x2a9 fp=0xc420b8fdb0 sp=0xc420b8fc80
github.com/cgrates/cgrates/engine.(*DataManager).SetStatQueue(0xc4203b6ea0,
0xc4203093e0, 0xc4219ece68, 0x10)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/datamanager.go:285
+0x5c fp=0xc420b8fe18 sp=0xc420b8fdb0
github.com/cgrates/cgrates/engine.(*StatService).StoreStatQueue(0xc42006bb00,
0xc4203093e0, 0xa, 0xc420fd49c0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/stats.go:134
+0x88 fp=0xc420b8feb0 sp=0xc420b8fe18
github.com/cgrates/cgrates/engine.(*StatService).storeStats(0xc42006bb00)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/stats.go:114
+0x12c fp=0xc420b8ffa8 sp=0xc420b8feb0
github.com/cgrates/cgrates/engine.(*StatService).runBackup(0xc42006bb00)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/stats.go:92
+0x68 fp=0xc420b8ffd8 sp=0xc420b8ffa8
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420b8ffe0
sp=0xc420b8ffd8
created by github.com/cgrates/cgrates/engine.(*StatService).ListenAndServe
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/stats.go:66
+0x43
goroutine 1 [chan receive, 3 minutes]:
main.main()
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:1000
+0xe95
goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 7 [sleep, 1 minutes]:
time.Sleep(0xdf8475800)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache.(*Cache).cleanExpired(0xc42027fdc0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache/cache.go:245
+0x183
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache.NewCache
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache/cache.go:69
+0x2b4
goroutine 8 [sleep, 1 minutes]:
time.Sleep(0xdf8475800)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache.(*Cache).cleanExpired(0xc42027fea0)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache/cache.go:245
+0x183
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache.NewCache
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache/cache.go:69
+0x2b4
goroutine 9 [sleep, 1 minutes]:
time.Sleep(0xdf8475800)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache.(*Cache).cleanExpired(0xc4202aa540)
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache/cache.go:245
+0x183
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache.NewCache
    /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/ltcache/cache.go:69
+0x2b4
goroutine 14 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
```

Could anyone help with this issue?

**Comment by danbogos** [comment]
Hi @alexsosic 

The new modules were not yet tested on load so there are chances that we need to add some locks here and there.

To detect races conditions, please recompile the binary with -race flag (go install -race) and repeat your tests, posting panics herre. I expect all sort of races to show up but we have a global locking mechanism, so it should be fairly simple to fix them once you report them here.

Ta
DanB

**Comment by danbogos** [comment]
Hey @alexsosic 

Did u get a chance to run the -race flag?

Thanks,
DanB

**Comment by danbogos** [comment]
hey @alexsosic 

I have just added locking around StatQueue. This should fix the panic reported here.
Please retest and report back (re-open if issue persists).

Thanks,
DanB
