### ISSUE TITLE
Crash with : in Destination

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1258]
Hi,

When using this

```
{"tag": "Destination", "field_id": "Destination", "type": "*composed",
                                                "value": "~*req.MCC;/;~*req.MNC;:;~*req.profile:s/Global /G+/", "mandatory": true},
```

on `profile=Global `

I get:

```
panic: runtime error: index out of range

goroutine 200 [running]:
github.com/cgrates/cgrates/engine.(*RITiming).getLeftMargin(0xc0004d72c0, 0x312208c3, 0xed3601cd0, 0x1953cc0, 0xc0006d8ec0, 0x4d9a89, 0x11b9ea0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:152 +0x274
github.com/cgrates/cgrates/engine.(*RITiming).IsActiveAt(0xc0004d72c0, 0x312208c3, 0xed3601cd0, 0x1953cc0, 0xb48c07)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:181 +0x79
github.com/cgrates/cgrates/engine.(*RateInterval).Contains(0xc0000bea60, 0x312208c3, 0xed3601cd0, 0x1953cc0, 0x100, 0xc0006d8fb0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:322 +0x59
github.com/cgrates/cgrates/engine.RatingInfo.SelectRatingIntevalsForTimespan(0xc000444560, 0x19, 0xc0003a6780, 0xa, 0xc000177520, 0xa, 0xc0003d90e0, 0x19, 0x0, 0xed35d2be0, ...)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/ratingprofile.go:100 +0x148
github.com/cgrates/cgrates/engine.(*CallDescriptor).splitInTimeSpans(0xc00010bce0, 0x0, 0x0, 0x312208c3)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:508 +0xdca
github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc00010bce0, 0x18, 0xc0000e1bc0, 0x0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:646 +0x5cc
github.com/cgrates/cgrates/engine.(*Balance).GetCost(0xc00017dee0, 0xc00010bce0, 0xed3601c01, 0x1953cc0, 0x1, 0x1)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/balances.go:280 +0x8c
github.com/cgrates/cgrates/engine.(*Balance).debitMoney(0xc00017dee0, 0xc00010bce0, 0xc00039cfc0, 0xc0001af3e8, 0x1, 0x1, 0x10100, 0x1015f82, 0x9, 0xc0001af3e8)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/balances.go:549 +0xc8
github.com/cgrates/cgrates/engine.(*Account).debitCreditBalance(0xc00039cfc0, 0xc00010bce0, 0x100, 0xc00066b7a0, 0x24, 0x24)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/account.go:440 +0x92f
github.com/cgrates/cgrates/engine.(*CallDescriptor).debit(0xc00010bce0, 0xc00039cfc0, 0x1950001, 0x312208c3, 0xed3601cd0, 0x1953cc0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:791 +0xe0
github.com/cgrates/cgrates/engine.(*CallDescriptor).getMaxSessionDuration(0xc00010b4a0, 0xc00039cf00, 0xf42d40, 0xc000177548, 0x16)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:699 +0x19c
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetMaxSessionDuration.func1.1(0xc000164000, 0xc00050c000, 0xc00050c010, 0xc000318880)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:762 +0x3c
github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard.func1(0xc0001542e0, 0xc0003fd320, 0xc0003fd380)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:86 +0x2b
created by github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:84 +0x115

```

**Comment by ghenry** [comment]
I can trigger the same with:

"Destination":"234/015:G+"

T 2018/10/22 20:49:34.023225 127.0.0.1:35794 -> 127.0.0.1:2012 [AP]
{"method":"SessionSv1.AuthorizeEvent","params":[{"GetAttributes":true,"AuthorizeResources":false,"GetMaxUsage":true,"ProcessThresholds":false,"ProcessStats":false,"GetSuppliers":false,"SuppliersMaxCost":"","SuppliersIgnoreErrors":false,"Tenant":"surevoip","ID":"ccea523","Context":null,"Time":"2018-10-22T20:49:34.022854362+01:00","Event":{"Account":"XXX","Category":"m_data","Destination":"234/015:G+","OriginID":"145413820","RequestType":"*pseudoprepaid","SetupTime":"*now"},"Limit":null,"Offset":null,"SearchTerm":""}],"id":0}

##
T 2018/10/22 20:49:34.023743 127.0.0.1:35798 -> 127.0.0.1:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"ProcessRuns":null,"Tenant":"surevoip","ID":"ccea523","Context":"*sessions","Time":"2018-10-22T20:49:34.022854362+01:00","Event":{"Account":"XXX","Category":"m_data","Destination":"234/015:G+","OriginID":"145413820","RequestType":"*pseudoprepaid","SetupTime":"*now"}}],"id":0}

##
T 2018/10/22 20:49:34.028961 127.0.0.1:2012 -> 127.0.0.1:35798 [AP]
{"id":0,"result":null,"error":"NOT_FOUND"}

##
T 2018/10/22 20:49:34.029337 127.0.0.1:35795 -> 127.0.0.1:2012 [AP]
{"method":"ChargerSv1.ProcessEvent","params":[{"Tenant":"surevoip","ID":"f2cbfce","Context":null,"Time":null,"Event":{"Account":"XXX","CGRID":"a58792e10b726ce0db4bea24be47923bd2c061bd","Category":"m_data","Destination":"234/015:G+","OriginID":"145413820","RequestType":"*pseudoprepaid","SetupTime":"*now","Usage":10800000000000}}],"id":0}

##
T 2018/10/22 20:49:34.033170 127.0.0.1:2012 -> 127.0.0.1:35795 [AP]
{"id":0,"result":[{"ChargerSProfile":"DEFAULT","AttributeSProfiles":null,"AlteredFields":null,"CGREvent":{"Tenant":"surevoip","ID":"f2cbfce","Context":null,"Time":null,"Event":{"Account":"XXX","CGRID":"a58792e10b726ce0db4bea24be47923bd2c061bd","Category":"m_data","Destination":"234/015:G+","OriginID":"145413820","RequestType":"*pseudoprepaid","RunID":"*default","SetupTime":"*now","Usage":10800000000000}}}],"error":null}

##
T 2018/10/22 20:49:34.034279 127.0.0.1:35797 -> 127.0.0.1:2012 [AP]
{"method":"Responder.GetMaxSessionTime","params":[{"Direction":"*out","Category":"m_data","Tenant":"surevoip","Subject":"","Account":"XXX","Destination":"234/015:G+","TimeStart":"2018-10-22T20:49:34.033783871+01:00","TimeEnd":"2018-10-22T23:49:34.033783871+01:00","LoopIndex":0,"DurationIndex":0,"FallbackSubject":"","RatingInfos":null,"Increments":null,"TOR":"","ExtraFields":{},"MaxRate":0,"MaxRateUnit":0,"MaxCostSoFar":0,"CgrID":"a58792e10b726ce0db4bea24be47923bd2c061bd","RunID":"*default","ForceDuration":false,"PerformRounding":false,"DryRun":false,"DenyNegativeAccount":false}],"id":0}

**Comment by ghenry** [comment]
I think it's actually all because of havin `:` in my destination as this crashes it with the same error:

`"Destination":"234/015:G"`

Should I not use `:` or is this a bug?

**Comment by ghenry** [comment]
I get the same with:

`"Destination":"234/015/G+"`

so the + is still an issue.

**Comment by ghenry** [comment]
Re-reading the detailed crash, I think this is actually to do with my Rates.csv for data usage.

**Comment by ghenry** [comment]
This was due to my data RateUnit being lower than my RateIncrement as I had messed up kb and mb. Apologies.

**Comment by ghenry** [comment]
Unless my cache in RALS still have some older data, it's still crashing now. Redis is empty. I'll leave this closed and take it to the mailing list.

**Comment by ghenry** [comment]
Opening this as it does seem valid now:

```
panic: runtime error: index out of range

goroutine 200 [running]:
github.com/cgrates/cgrates/engine.(*RITiming).getLeftMargin(0xc0001c0be0, 0x2de5e6d1, 0xed3603ab4, 0x1953cc0, 0xc000627290, 0x4d9a89, 0x11b9ea0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:152 +0x274
github.com/cgrates/cgrates/engine.(*RITiming).IsActiveAt(0xc0001c0be0, 0x2de5e6d1, 0xed3603ab4, 0x1953cc0, 0xb48c07)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:181 +0x79
github.com/cgrates/cgrates/engine.(*RateInterval).Contains(0xc0004b7f20, 0x2de5e6d1, 0xed3603ab4, 0x1953cc0, 0x100, 0xc000627380)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:322 +0x59
github.com/cgrates/cgrates/engine.RatingInfo.SelectRatingIntevalsForTimespan(0xc0002208a0, 0x19, 0xc0004e2360, 0xa, 0xc00013f760, 0xa, 0xc000220a20, 0x19, 0x0, 0xed35d2be0, ...)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/ratingprofile.go:100 +0x148
github.com/cgrates/cgrates/engine.(*CallDescriptor).splitInTimeSpans(0xc00064c6e0, 0x0, 0x0, 0x2de5e6d1)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:508 +0xdca
github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc00064c6e0, 0xc00027a160, 0xa, 0xc00013f504)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:646 +0x5cc
github.com/cgrates/cgrates/engine.(*Account).debitCreditBalance(0xc0001444c0, 0xc00064c6e0, 0x100, 0x203000, 0x24, 0x24)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/account.go:481 +0xc88
github.com/cgrates/cgrates/engine.(*CallDescriptor).debit(0xc00064c6e0, 0xc0001444c0, 0x1950001, 0x2de5e6d1, 0xed3603ab4, 0x1953cc0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:791 +0xe0
github.com/cgrates/cgrates/engine.(*CallDescriptor).getMaxSessionDuration(0xc00064c160, 0xc000144440, 0xf42d40, 0xc00013f780, 0x16)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:699 +0x19c
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetMaxSessionDuration.func1.1(0xc00015a000, 0xc0004e3c20, 0xc0004e3c50, 0xc000356280)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:762 +0x3c
github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard.func1(0xc0004b7600, 0xc00041f320, 0xc00041f380)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:86 +0x2b
created by github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:84 +0x115
```
Redis is fine:

```
keys rds_234/*
1) "rds_234/015:G+"
2) "rds_234/033:G+"
3) "rds_234/010:G+"
4) "rds_234/030:G+"

keys dst_United*King*
1) "dst_United Kingdom - T-Mobile (UK) Limited"
2) "dst_United Kingdom - Vodafone"
3) "dst_United Kingdom - O2 (UK) Limited"
4) "dst_United Kingdom - Orange PCS Ltd"

```
Internal:

```
###################
T 2018/10/22 22:40:04.757889 127.0.0.1:37897 -> 127.0.0.1:2012 [AP]
{"method":"SessionSv1.AuthorizeEvent","params":[{"GetAttributes":true,"AuthorizeResources":false,"GetMaxUsage":true,"ProcessThresholds":false,"ProcessStats":false,"GetSuppliers":false,"SuppliersMaxCost":"","SuppliersIgnoreErrors":false,"Tenant":"surevoip","ID":"5fa202c","Context":null,"Time":"2018-10-22T22:40:04.757411555+01:00","Event":{"Account":"XXX","Category":"m_data","Destination":"234/015:G+","OriginID":"145414474","RequestType":"*pseudoprepaid","SetupTime":"*now"},"Limit":null,"Offset":null,"SearchTerm":""}],"id":0}

##
T 2018/10/22 22:40:04.758388 127.0.0.1:37901 -> 127.0.0.1:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"ProcessRuns":null,"Tenant":"surevoip","ID":"5fa202c","Context":"*sessions","Time":"2018-10-22T22:40:04.757411555+01:00","Event":{"Account":"XXX","Category":"m_data","Destination":"234/015:G+","OriginID":"145414474","RequestType":"*pseudoprepaid","SetupTime":"*now"}}],"id":0}

##
T 2018/10/22 22:40:04.765380 127.0.0.1:2012 -> 127.0.0.1:37901 [AP]
{"id":0,"result":null,"error":"NOT_FOUND"}

##
T 2018/10/22 22:40:04.765679 127.0.0.1:37896 -> 127.0.0.1:2012 [AP]
{"method":"ChargerSv1.ProcessEvent","params":[{"Tenant":"surevoip","ID":"f17b3d5","Context":null,"Time":null,"Event":{"Account":"XXX","CGRID":"86acfa2ef7a1ca1278b037943457687b0640a4e2","Category":"m_data","Destination":"234/015:G+","OriginID":"145414474","RequestType":"*pseudoprepaid","SetupTime":"*now","Usage":10800000000000}}],"id":0}

##
T 2018/10/22 22:40:04.769458 127.0.0.1:2012 -> 127.0.0.1:37896 [AP]
{"id":0,"result":[{"ChargerSProfile":"DEFAULT","AttributeSProfiles":null,"AlteredFields":null,"CGREvent":{"Tenant":"surevoip","ID":"f17b3d5","Context":null,"Time":null,"Event":{"Account":"XXX","CGRID":"86acfa2ef7a1ca1278b037943457687b0640a4e2","Category":"m_data","Destination":"234/015:G+","OriginID":"145414474","RequestType":"*pseudoprepaid","RunID":"*default","SetupTime":"*now","Usage":10800000000000}}}],"error":null}

##
T 2018/10/22 22:40:04.770501 127.0.0.1:37898 -> 127.0.0.1:2012 [AP]
{"method":"Responder.GetMaxSessionTime","params":[{"Direction":"*out","Category":"m_data","Tenant":"surevoip","Subject":"","Account":"XXX","Destination":"234/015:G+","TimeStart":"2018-10-22T22:40:04.770041553+01:00","TimeEnd":"2018-10-23T01:40:04.770041553+01:00","LoopIndex":0,"DurationIndex":0,"FallbackSubject":"","RatingInfos":null,"Increments":null,"TOR":"","ExtraFields":{},"MaxRate":0,"MaxRateUnit":0,"MaxCostSoFar":0,"CgrID":"86acfa2ef7a1ca1278b037943457687b0640a4e2","RunID":"*default","ForceDuration":false,"PerformRounding":false,"DryRun":false,"DenyNegativeAccount":false}],"id":0}
```

**Comment by TeoV** [comment]
Hi @ghenry,

Can you please provide a data sample to reproduce this issue and the exact steps?

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi TeoV, 

Reproduced with minimal data. See attached logs and CSV. The GET request kills cgrates. See log txt file.

Thanks.

[logs_from_various_places.txt](https://github.com/cgrates/cgrates/files/2505664/logs_from_various_places.txt)
[cgrates_csv.tar.gz](https://github.com/cgrates/cgrates/files/2505650/cgrates_csv.tar.gz)

cgrates.json:

```
{
  "general": {
    "node": "xxx.suretec.net",
    "rounding_decimals": 6,
    "default_tenant": "surevoip"
  },
  "listen": {
    "rpc_json": "0.0.0.0:2012",
    "rpc_gob": "0.0.0.0:2013",
    "http": "0.0.0.0:2080",
    "http_tls": "0.0.0.0:2280",
    "tls_server_certificate": "/etc/cgrates/wildcard.suretec.net.with-intermediate.crt",		
    "tls_server_key":"/etc/cgrates/wildcard.suretec.net.key"
  },
  "data_db": {
    "db_type": "redis",
    "db_host": "XXX",
    "db_name": "10",
    "db_password": "XXX",
    "redis_sentinel": "master"
  },
  "stor_db": {
    "db_type": "postgres",					// stor database type to use: <mysql|postgres>
    "db_host": "XXX",
    "db_port": 5432, 					// the port to reach the stordb
    "db_name": "XXX",
    "db_user": "XXX",
    "db_password": "XXX",
    "max_open_conns": 50,
    "max_idle_conns": 10,
    "conn_max_lifetime": 0
  },
  "scheduler": {
    "enabled": true
  },
  "rals": {
    "enabled": true
  },
  "cdrs": {
    "enabled": true
  },
  "sessions": {
    "enabled": true,
    "chargers_conns": [
      {"address": "127.0.0.1:2012", "transport":"*json"}
    ],
    "rals_conns": [
      {"address": "127.0.0.1:2012", "transport":"*json"}
    ],
    "cdrs_conns": [
      {"address": "*internal"},
    ],
    "resources_conns": [
      {"address": "*internal"},
    ],
    "suppliers_conns": [
      {"address": "*internal"},
    ],
    "attributes_conns": [
      {"address": "127.0.0.1:2012", "transport":"*json"}
    ],
    "debit_interval": "10s"
  },
  "freeswitch_agent": {
    "enabled": true,
    "sessions_conns": [
      {"address": "*internal"}
    ],
    "subscribe_park": true,
    "create_cdr": true,
    "channel_sync_interval": "5m",
    "max_wait_connection": "2s",
    "event_socket_conns": [
      {"address": "127.0.0.1:8021", "password": "XXX", "reconnects": 5}
    ]
  },
  "attributes": {
    "enabled": true
  },
  "chargers": {
    "enabled": true,
    "attributes_conns": [
      {"address": "127.0.0.1:2012", "transport":"*json"}
    ]
  },

  "resources": {
    "enabled": true 
  },
  "stats": {
    "enabled": true
  },
  "thresholds": {
    "enabled": true
  },
  "suppliers": {
    "enabled": true
  }
}
```

**Comment by TeoV** [comment]
Hi @ghenry, 

We cannot reproduce the crash with the data that you've provided.
Most probably the rates were cached in your case. 
We have noticed however that you have misconfigured balance ( you are using destination prefix instead of destination ids ).

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi @TeoV ,

I've cache_clear, cleared redis and switch the balance, but still the exact same crash.

Thanks.

**Comment by TeoV** [comment]
Hi @ghenry, 
Here is what I did : 
1) Flush the database (redis-cli -n 10 flushdb) 
2) Start the engine with tutmysql 
3) As I said before you have misconfigured balance ( in Actions.csv for Destination[6] you should have DestinationID not prefix ) somethink like this : 
```
#ActionsId[0],Action[1],ExtraParameters[2],Filter[3],BalanceId[4],BalanceType[5],Directions[6],Categories[7],DestinationIds[8],RatingSubject[9],SharedGroup[10],ExpiryTime[11],TimingIds[12],Units[13],BalanceWeight[14],BalanceBlocker[15],BalanceDisabled[16],Weight[17]
TOPUP_RST_DATA_UK_500,*topup_reset,,,BUNDLE_UK_MOBILE_DATA_500,*data,*out,,United Kingdom - O2 (UK) Limited;United Kingdom - T-Mobile (UK) Limited;United Kingdom - Orange PCS Ltd;United Kingdom - Vodafone,,,*unlimited,,512000,10,false,false,10
LOG_WARNING,*log,,,,,,,,,,,,,,false,false,10
DISABLE_AND_LOG,*log,,,,,,,,,,,,,,false,false,10
DISABLE_AND_LOG,*disable_account,,,,,,,,,,,,,,false,false,10
```
4) Load the data with cgr-loader 
5) Send the request to CGRateS and got response. 

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi @TeoV ,

I've done that using the data from above (with the balance corretino), but my config and see the crash and this:

panic: runtime error: index out of range

```
goroutine 96 [running]:
github.com/cgrates/cgrates/engine.(*RITiming).getLeftMargin(0xc0005a8280, 0x27909d9a, 0xed3625861, 0x195acc0, 0xc00055b290, 0x4d9a89, 0x11be000)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:152 +0x274
github.com/cgrates/cgrates/engine.(*RITiming).IsActiveAt(0xc0005a8280, 0x27909d9a, 0xed3625861, 0x195acc0, 0xb4aa07)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:181 +0x79
github.com/cgrates/cgrates/engine.(*RateInterval).Contains(0xc0001e09e0, 0x27909d9a, 0xed3625861, 0x195acc0, 0x100, 0xc00055b380)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:322 +0x59
github.com/cgrates/cgrates/engine.RatingInfo.SelectRatingIntevalsForTimespan(0xc0007610e0, 0x19, 0xc0001a8920, 0xa, 0xc0001a8420, 0xa, 0xc000761500, 0x19, 0x0, 0xed35d2be0, ...)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/ratingprofile.go:100 +0x148
github.com/cgrates/cgrates/engine.(*CallDescriptor).splitInTimeSpans(0xc0006fe840, 0x0, 0x0, 0x27909d9a)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:509 +0xdca
github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc0006fe840, 0xc0001ed970, 0xa, 0xc0001a8400)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:647 +0x5cc
github.com/cgrates/cgrates/engine.(*Account).debitCreditBalance(0xc000516400, 0xc0006fe840, 0x100, 0x203000, 0x24, 0x24)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/account.go:481 +0xc88
github.com/cgrates/cgrates/engine.(*CallDescriptor).debit(0xc0006fe840, 0xc000516400, 0x1950001, 0x27909d9a, 0xed3625861, 0x195acc0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:792 +0xe0
github.com/cgrates/cgrates/engine.(*CallDescriptor).getMaxSessionDuration(0xc0006fe2c0, 0xc000516380, 0x0, 0x0, 0xc00010a720)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:700 +0x19c
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetMaxSessionDuration.func1.1(0x0, 0xc00010a780, 0x0, 0x1)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:763 +0x3c
github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard.func1(0xc0003dbda0, 0xc000534660, 0xc0005346c0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:86 +0x2b
created by github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:84 +0x115
```

activity:

```
T 2018/10/24 13:11:13.653712 127.0.0.1:39687 -> 127.0.0.1:2012 [AP]
{"method":"SessionSv1.AuthorizeEvent","params":[{"GetAttributes":true,"AuthorizeResources":false,"GetMaxUsage":true,"ProcessThresholds":false,"ProcessStats":false,"GetSuppliers":false,"SuppliersMaxCost":"","SuppliersIgnoreErrors":false,"Tenant":"surevoip","ID":"273f00f","Context":null,"Time":"2018-10-24T13:11:13.653345768+01:00","Event":{"Account":"234189200172500","Category":"m_data","Destination":"234/015:G+","OriginID":"145425232","RequestType":"*pseudoprepaid","SetupTime":"*now"},"Limit":null,"Offset":null,"SearchTerm":""}],"id":0}

##
T 2018/10/24 13:11:13.654260 127.0.0.1:39686 -> 127.0.0.1:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"ProcessRuns":null,"Tenant":"surevoip","ID":"273f00f","Context":"*sessions","Time":"2018-10-24T13:11:13.653345768+01:00","Event":{"Account":"234189200172500","Category":"m_data","Destination":"234/015:G+","OriginID":"145425232","RequestType":"*pseudoprepaid","SetupTime":"*now"}}],"id":0}

##
T 2018/10/24 13:11:13.659546 127.0.0.1:2012 -> 127.0.0.1:39686 [AP]
{"id":0,"result":null,"error":"NOT_FOUND"}

##
T 2018/10/24 13:11:13.659822 127.0.0.1:39684 -> 127.0.0.1:2012 [AP]
{"method":"ChargerSv1.ProcessEvent","params":[{"Tenant":"surevoip","ID":"d0734b6","Context":null,"Time":null,"Event":{"Account":"234189200172500","CGRID":"4e8599111d07b43c96857b680d2fe7ecb440ed37","Category":"m_data","Destination":"234/015:G+","OriginID":"145425232","RequestType":"*pseudoprepaid","SetupTime":"*now","Usage":10800000000000}}],"id":0}

##
T 2018/10/24 13:11:13.663115 127.0.0.1:2012 -> 127.0.0.1:39684 [AP]
{"id":0,"result":[{"ChargerSProfile":"DEFAULT","AttributeSProfiles":null,"AlteredFields":null,"CGREvent":{"Tenant":"surevoip","ID":"d0734b6","Context":null,"Time":null,"Event":{"Account":"234189200172500","CGRID":"4e8599111d07b43c96857b680d2fe7ecb440ed37","Category":"m_data","Destination":"234/015:G+","OriginID":"145425232","RequestType":"*pseudoprepaid","RunID":"*default","SetupTime":"*now","Usage":10800000000000}}}],"error":null}

##
T 2018/10/24 13:11:13.664190 127.0.0.1:39685 -> 127.0.0.1:2012 [AP]
{"method":"Responder.GetMaxSessionTime","params":[{"Direction":"*out","Category":"m_data","Tenant":"surevoip","Subject":"","Account":"234189200172500","Destination":"234/015:G+","TimeStart":"2018-10-24T13:11:13.663788954+01:00","TimeEnd":"2018-10-24T16:11:13.663788954+01:00","LoopIndex":0,"DurationIndex":0,"FallbackSubject":"","RatingInfos":null,"Increments":null,"TOR":"","ExtraFields":{},"MaxRate":0,"MaxRateUnit":0,"MaxCostSoFar":0,"CgrID":"4e8599111d07b43c96857b680d2fe7ecb440ed37","RunID":"*default","ForceDuration":false,"PerformRounding":false,"DryRun":false,"DenyNegativeAccount":false}],"id":0}
```

**Comment by ghenry** [comment]
I presume you used the http_agent config I provided?

**Comment by ghenry** [comment]
Closing. This was due to Timings.csv error and a ToR for data missing. Thanks for the help!
