### ISSUE TITLE
All memory consumed

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1263]
Hi,

If I issue this normal request with similar configuration attached to #1258 (just with more rates) with in seconds 15GB of RAM is consumed and starts eating all swap (32GB) on this server with the latest master deb:

curl "http://127.0.0.1:2080/conecto?timestamp=2018-10-23%2019:55:03&imsi=204046848972500&transactionid=118867&destination=447440935378&from=447958879850&mcc=234&mnc=15&request_type=MT_SMS&user_balance=0.0000&carrierid=&tadig=GBRVF&globalmsisdn=447440935378&globalimsi=234189200172500&iccid=89014601604000725009&ProfileId=6"

**Comment by ghenry** [comment]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                             
12488 suretec   20   0 26.875g 0.015t      0 S  16.1 97.4   1:52.70 cgr-engine
```

**Comment by TeoV** [comment]
Hi @ghenry,

Please verify rating increment vs amount of data used.
Firstly you can do a cost simulation. 

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi @TeoV ,
Can you explain both for me again?
Thanks.

**Comment by ghenry** [comment]
I've just re-loaded my data using the correct balances and run the curl command above and get the same crash as in #1258 

```
panic: runtime error: index out of range

goroutine 183 [running]:
github.com/cgrates/cgrates/engine.(*RITiming).getLeftMargin(0xc000528dc0, 0xfbf3b2c, 0xed36259ad, 0x195acc0, 0xc000637290, 0x4d9a89, 0x11be000)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:152 +0x274
github.com/cgrates/cgrates/engine.(*RITiming).IsActiveAt(0xc000528dc0, 0xfbf3b2c, 0xed36259ad, 0x195acc0, 0xb4aa07)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:181 +0x79
github.com/cgrates/cgrates/engine.(*RateInterval).Contains(0xc000267c00, 0xfbf3b2c, 0xed36259ad, 0x195acc0, 0x100, 0xc000637380)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/rateinterval.go:322 +0x59
github.com/cgrates/cgrates/engine.RatingInfo.SelectRatingIntevalsForTimespan(0xc0004e7960, 0x19, 0xc0003a5550, 0x9, 0x1012cb1, 0x4, 0x1012cb1, 0x4, 0x0, 0xed35d2be0, ...)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/ratingprofile.go:100 +0x148
github.com/cgrates/cgrates/engine.(*CallDescriptor).splitInTimeSpans(0xc0002f6b00, 0x0, 0x0, 0xfbf3b2c)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:509 +0xdca
github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc0002f6b00, 0xc0003f8580, 0xc, 0xc000154680)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:647 +0x5cc
github.com/cgrates/cgrates/engine.(*Account).debitCreditBalance(0xc000452880, 0xc0002f6b00, 0x100, 0x203000, 0x24, 0x24)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/account.go:481 +0xc88
github.com/cgrates/cgrates/engine.(*CallDescriptor).debit(0xc0002f6b00, 0xc000452880, 0x1950001, 0xfbf3b2c, 0xed36259ad, 0x195acc0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:792 +0xe0
github.com/cgrates/cgrates/engine.(*CallDescriptor).getMaxSessionDuration(0xc000590840, 0xc000452800, 0xe1a020, 0xc0000e2a80, 0x16)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:700 +0x19c
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetMaxSessionDuration.func1.1(0xc000162000, 0xc0003a4008, 0xc0003a4030, 0x0)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/calldesc.go:763 +0x3c
github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard.func1(0xc0000e37e0, 0xc00064e900, 0xc00064e960)
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:86 +0x2b
created by github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard
	/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/guardian/guardian.go:84 +0x115

```

**Comment by ghenry** [comment]
Closing. This was due ToR *data missing and defaulting to *voice and filling all memory with tons cost increments.
