### ISSUE TITLE
CGRates Crashes after the upgrade to latest release 

### ISSUE THREAD

**Issue by rahmanafzal86** [cgrates/cgrates#1441]
[cgrates.json.txt](https://github.com/cgrates/cgrates/files/2905326/cgrates.json.txt)

Hi,

I have upgraded to CGrates to latest release (CGRateS 0.9.1~rc8 git+6b1daab (2019-02-22T20:19:57+01:00)) and after that cgrates crashing with the following below error; 

our cgrates.json is attached FYI.

 /etc/init.d/cgrates status
â cgrates.service - Control CGRateS - carrier grade real-time charging system
   Loaded: loaded (/lib/systemd/system/cgrates.service; enabled)
   Active: active (running) since Tue 2019-02-26 14:11:12 GMT; 4min 43s ago
 Main PID: 7470 (cgr-engine)
   CGroup: /system.slice/cgrates.service
           ââ7470 /usr/bin/cgr-engine

Feb 26 14:13:08 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:13:22 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:13:55 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:13:55 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:14:08 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:14:22 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:14:55 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:15:08 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:15:22 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:15:55 localhost cgr-engine[7470]: CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND

#### starting logs

Feb 26 14:11:12 localhost systemd[1]: Stopping Control CGRateS - carrier grade real-time charging system...
Feb 26 14:11:12 localhost systemd[1]: Starting Control CGRateS - carrier grade real-time charging system...
Feb 26 14:11:12 localhost systemd[1]: Started Control CGRateS - carrier grade real-time charging system.
Feb 26 14:11:12 localhost CGRateS <ringmi> [7470]: Starting FreeSWITCH agent
Feb 26 14:11:12 localhost CGRateS <ringmi> [7470]: Starting CGRateS Session service.
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <ServiceManager> Starting CGRateS Scheduler.
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <CDRC> No enabled CDRC clients
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Starting CGRateS CDRS service.
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: WARNING: missing TLS certificate/key file!
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: WARNING: missing TLS certificate/key file!
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: WARNING: missing TLS certificate/key file!
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <HTTP> enabling handler for JSON-RPC
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <HTTP> enabling handler for WebSocket connections
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <HTTP> start listening at <0.0.0.0:2080>
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Registering CDRS HTTP Handlers.
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Registering CDRS RPC service.
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Starting CGRateS GOB server at <0.0.0.0:2013>.
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Starting CGRateS JSON server at <0.0.0.0:2012>.
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "RegisterHandlersToServer" has 2 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Starting ChargerS
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <FSock> Successfully connected to FreeSWITCH!
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: Starting CGRateS BiJSON server at <127.0.0.1:2014>
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCV1GetMaxUsage" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCV1InitiateSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCV1ProcessCDR" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCV1TerminateSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCV1UpdateSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "Handlers" has 1 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCPing" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1AuthorizeEvent" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1AuthorizeEventWithDigest" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1ForceDisconnect" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1GetActiveSessions" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1GetActiveSessionsCount" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1GetPassiveSessions" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1GetPassiveSessionsCount" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1InitiateSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1InitiateSessionWithDigest" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1ProcessCDR" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1ProcessEvent" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <FreeSWITCHAgent> successfully connected to FreeSWITCH at: <127.0.0.1:8021>
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1RegisterInternalBiJSONConn" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1ReplicateSessions" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1SetPassiveSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1SyncSessions" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1TerminateSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "BiRPCv1UpdateSession" has 4 input parameters; needs exactly three
Feb 26 14:11:13 localhost cgr-engine[7470]: 2019/02/26 14:11:13 rpc.Register: method "Handlers" has 1 input parameters; needs exactly three
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <Scheduler> processing 2 action plans
Feb 26 14:11:13 localhost CGRateS <ringmi> [7470]: <Scheduler> queued 0 action plans
Feb 26 14:11:22 localhost CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND
Feb 26 14:11:22 localhost CGRateS <ringmi> [7470]: Failed to get actions: NOT_FOUND

cgr-console status
{
 "ActiveGoroutines": 30,
 "Footprint": "70.2MiB",
 "MemoryUsage": "10.6MiB",
 "NodeID": "ringmi",
 "RunningSince": "Tue Feb 26 14:11:12 GMT 2019",
 "Version": "CGRateS 0.9.1~rc8 git+6b1daab (2019-02-22T20:19:57+01:00)"
}

######### Error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf18d35]

goroutine 293 [running]:
github.com/cgrates/cgrates/agents.(*FSsessions).disconnectSession(0xc0003afec0, 0x0, 0x0, 0xc0006ef0b9, 0x24, 0x0, 0x0, 0x129351c, 0x13, 0x1150920, ...)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/agents/fsagent.go:316 +0x185
github.com/cgrates/cgrates/agents.(*FSsessions).V1DisconnectSession(0xc0003afec0, 0xc0009dec60, 0x128ac0e, 0xc, 0xc00069d0c0, 0x0, 0x0)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/agents/fsagent.go:375 +0x232
reflect.Value.call(0x11d2240, 0xc0003afec0, 0xe13, 0x1281033, 0x4, 0xc00007fc60, 0x2, 0x2, 0xc00015b7b8, 0x13, ...)
        /usr/local/go/src/reflect/value.go:447 +0x454
reflect.Value.Call(0x11d2240, 0xc0003afec0, 0xe13, 0xc00007fc60, 0x2, 0x2, 0xc0003afec0, 0xe13, 0x203000)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/cgrates/cgrates/utils.RPCCall(0x11d2240, 0xc0003afec0, 0x129d85e, 0x1c, 0x11466a0, 0xc0001d9820, 0x1066f20, 0xc00069d0c0, 0xc0001d9820, 0xc0001d9820)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/utils/coreutils.go:815 +0x363
github.com/cgrates/cgrates/agents.(*FSsessions).Call(0xc0003afec0, 0x129d85e, 0x1c, 0x11466a0, 0xc0001d9820, 0x1066f20, 0xc00069d0c0, 0x7af592, 0xc0004d5f80)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/agents/fsagent.go:368 +0x80
github.com/cgrates/cgrates/sessions.(*SessionS).disconnectSession(0xc0001ac000, 0xc00085c090, 0x128ac0e, 0xc, 0x0, 0xc0000bb600)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:650 +0x241
github.com/cgrates/cgrates/sessions.(*SessionS).debitLoopSession(0xc0001ac000, 0xc00085c090, 0x0, 0x12a05f200, 0x24, 0x0, 0x0)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:519 +0x5f7
created by github.com/cgrates/cgrates/sessions.(*SessionS).initSession
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:1167 +0x26c

Please let us know if you need anything else from our side.

Thankyou.
Rahman Afzal

**Comment by rahmanafzal86** [comment]
Also I am attaching trace on port 8021 of a call:
ANI: 923136677711
DNIS:923468064011

[8021.txt](https://github.com/cgrates/cgrates/files/2906915/8021.txt)

and csv files also in zip file, these file for one tenant and also we have same files uploaded for different tenant as well.


[csv_files.zip](https://github.com/cgrates/cgrates/files/2906937/csv_files.zip)

**Comment by rahmanafzal86** [comment]
Hi,
Any update on this issue please?

Regards,
Rahman

**Comment by danbogos** [comment]
Hi Rahman,

We are having hard time to reproduce your issue. Based on the configuration you have attached, CGRateS should not even process calls (ie: you have the connection between ChargerS and AttributeS but no AttributeS started).
You have either a mixed versions of CGRateS running (ie: not the master) or you did not send us the correct configuration. Once we have corrected your attributes configuration, we were able to perform calls and also have them disconnected without panic.

DanB

**Comment by rahmanafzal86** [comment]
Hi Dan,

Thanks for the response, Can you please share the attribute configuration with us which you have made in order to resolve this issue.

Regards,
Rahman

**Comment by danbogos** [comment]
Rahman,

We did not say we have resolved the issue. We cannot reproduce it out of the data you have sent us, so there must be something else involved.

I suggest you review a proper configuration which you can find here:
https://github.com/cgrates/cgrates/blob/master/data/tutorials/fs_evsock/cgrates/etc/cgrates/cgrates.json

DanB

**Comment by rahmanafzal86** [comment]
Thanks Dan, with suggested modified configuration seems cgrates working stable but its weird when i run cgrates through init.d script its crashing as before but not from binary "cgr-engin &".

Regards,
Rahman

**Comment by danbogos** [comment]
Rahman,

I think you are having different binaries (old and new one) and that is also the reason of panics.

DanB

**Comment by danbogos** [comment]
Closing due to inactivity. Please reopen if the issue still occurs.

DanB
