### ISSUE TITLE
Crash CGRateS in kamevapi

### ISSUE THREAD

**Issue by sem32** [cgrates/cgrates#1469]
Using
 * GIT commit: 6fea2b3e6ba4fcc697dad8c0620317a31534aec9
 * kamevapi module
 * configuration threshold
```bash
2019/03/16 20:33:03 CGRateS <CGRKamailio> [INFO] Threshold hit, Balance: {"ID":"wildix.com:33374320880","BalanceMap":{"*monetary":[{"Uuid":"bd3d9245-eb43-4935-9c36-3abc490755f8","ID":"MONEY","Value":99.532,"ExpirationDate":"0001-01-01T00:00:00Z","Weight":0,"DestinationIDs":null,"RatingSubject":"","Categories":null,"SharedGroups":null,"Timings":null,"TimingIDs":null,"Disabled":false,"Factor":null,"Blocker":false}]},"UnitCounters":null,"ActionTriggers":[{"ID":"STANDARD_TRIGGERS","UniqueID":"2147a110-6f37-462a-abe3-9db660365e76","ThresholdType":"*min_balance","ThresholdValue":2,"Recurrent":false,"MinSleep":0,"ExpirationDate":"0001-01-01T00:00:00Z","ActivationDate":"0001-01-01T00:00:00Z","Balance":{"Uuid":null,"ID":null,"Type":"*monetary","Value":null,"ExpirationDate":null,"Weight":null,"DestinationIDs":null,"RatingSubject":null,"Categories":null,"SharedGroups":null,"TimingIDs":null,"Timings":null,"Disabled":null,"Factor":null,"Blocker":null},"Weight":10,"ActionsID":"LOG_WARNING","MinQueuedItems":0,"Executed":false,"LastExecutionTime":"0001-01-01T00:00:00Z"},{"ID":"STANDARD_TRIGGERS","UniqueID":"3a1b56b0-0ef7-40e7-89db-25f077b46139","ThresholdType":"*max_balance","ThresholdValue":20,"Recurrent":false,"MinSleep":0,"ExpirationDate":"0001-01-01T00:00:00Z","ActivationDate":"0001-01-01T00:00:00Z","Balance":{"Uuid":null,"ID":null,"Type":"*monetary","Value":null,"ExpirationDate":null,"Weight":null,"DestinationIDs":null,"RatingSubject":null,"Categories":null,"SharedGroups":null,"TimingIDs":null,"Timings":null,"Disabled":null,"Factor":null,"Blocker":null},"Weight":10,"ActionsID":"LOG_WARNING","MinQueuedItems":0,"Executed":true,"LastExecutionTime":"2019-03-16T20:33:03.866973114Z"},{"ID":"STANDARD_TRIGGERS","UniqueID":"77096c4b-f7fa-49ec-b815-8ad00c7bd162","ThresholdType":"*max_balance","ThresholdValue":50,"Recurrent":false,"MinSleep":0,"ExpirationDate":"0001-01-01T00:00:00Z","ActivationDate":"0001-01-01T00:00:00Z","Balance":{"Uuid":null,"ID":null,"Type":"*monetary","Value":null,"ExpirationDate":null,"Weight":null,"DestinationIDs":null,"RatingSubject":null,"Categories":null,"SharedGroups":null,"TimingIDs":null,"Timings":null,"Disabled":null,"Factor":null,"Blocker":null},"Weight":10,"ActionsID":"DISABLE_AND_LOG","MinQueuedItems":0,"Executed":false,"LastExecutionTime":"0001-01-01T00:00:00Z"}],"AllowNegative":false,"Disabled":false}
2019/03/16 20:33:03 CGRateS <CGRKamailio> [INFO] Threshold hit, Balance: {"ID":"wildix.com:33374320880","BalanceMap":{"*monetary":[{"Uuid":"bd3d9245-eb43-4935-9c36-3abc490755f8","ID":"MONEY","Value":99.532,"ExpirationDate":"0001-01-01T00:00:00Z","Weight":0,"DestinationIDs":null,"RatingSubject":"","Categories":null,"SharedGroups":null,"Timings":null,"TimingIDs":null,"Disabled":false,"Factor":null,"Blocker":false}]},"UnitCounters":null,"ActionTriggers":[{"ID":"STANDARD_TRIGGERS","UniqueID":"2147a110-6f37-462a-abe3-9db660365e76","ThresholdType":"*min_balance","ThresholdValue":2,"Recurrent":false,"MinSleep":0,"ExpirationDate":"0001-01-01T00:00:00Z","ActivationDate":"0001-01-01T00:00:00Z","Balance":{"Uuid":null,"ID":null,"Type":"*monetary","Value":null,"ExpirationDate":null,"Weight":null,"DestinationIDs":null,"RatingSubject":null,"Categories":null,"SharedGroups":null,"TimingIDs":null,"Timings":null,"Disabled":null,"Factor":null,"Blocker":null},"Weight":10,"ActionsID":"LOG_WARNING","MinQueuedItems":0,"Executed":false,"LastExecutionTime":"0001-01-01T00:00:00Z"},{"ID":"STANDARD_TRIGGERS","UniqueID":"3a1b56b0-0ef7-40e7-89db-25f077b46139","ThresholdType":"*max_balance","ThresholdValue":20,"Recurrent":false,"MinSleep":0,"ExpirationDate":"0001-01-01T00:00:00Z","ActivationDate":"0001-01-01T00:00:00Z","Balance":{"Uuid":null,"ID":null,"Type":"*monetary","Value":null,"ExpirationDate":null,"Weight":null,"DestinationIDs":null,"RatingSubject":null,"Categories":null,"SharedGroups":null,"TimingIDs":null,"Timings":null,"Disabled":null,"Factor":null,"Blocker":null},"Weight":10,"ActionsID":"LOG_WARNING","MinQueuedItems":0,"Executed":true,"LastExecutionTime":"2019-03-16T20:33:03.866973114Z"},{"ID":"STANDARD_TRIGGERS","UniqueID":"77096c4b-f7fa-49ec-b815-8ad00c7bd162","ThresholdType":"*max_balance","ThresholdValue":50,"Recurrent":false,"MinSleep":0,"ExpirationDate":"0001-01-01T00:00:00Z","ActivationDate":"0001-01-01T00:00:00Z","Balance":{"Uuid":null,"ID":null,"Type":"*monetary","Value":null,"ExpirationDate":null,"Weight":null,"DestinationIDs":null,"RatingSubject":null,"Categories":null,"SharedGroups":null,"TimingIDs":null,"Timings":null,"Disabled":null,"Factor":null,"Blocker":null},"Weight":10,"ActionsID":"DISABLE_AND_LOG","MinQueuedItems":0,"Executed":true,"LastExecutionTime":"2019-03-16T20:33:03.867769338Z"}],"AllowNegative":false,"Disabled":false}
2019/03/16 20:33:03 CGRateS <CGRKamailio> [WARNING] <SessionS> could not complete debit operation on session: <791e1ff074ae2bf4c43c961ff0cb0a96e0d390c3>, error: <ACCOUNT_DISABLED>
2019/03/16 20:33:03 CGRateS <CGRKamailio> [WARNING] <SessionS> could not complete debit operation on session: <791e1ff074ae2bf4c43c961ff0cb0a96e0d390c3>, error: <ACCOUNT_DISABLED>
2019/03/16 20:33:03 CGRateS <CGRKamailio> [WARNING] <SessionS> could not complete debit operation on session: <791e1ff074ae2bf4c43c961ff0cb0a96e0d390c3>, error: <ACCOUNT_DISABLED>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xe83dfb]

goroutine 221 [running]:
github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi.(*KamEvapi).Connected(0x0, 0xc4206af100)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi/kamevapi.go:128 +0x2b
github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi.(*KamEvapi).ReconnectIfNeeded(0x0, 0x86, 0xc4206af140)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi/kamevapi.go:190 +0x2f
github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi.(*KamEvapi).Send(0x0, 0xc4206af140, 0x5c, 0x0, 0x1b3df40)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi/kamevapi.go:242 +0x2b
github.com/cgrates/cgrates/agents.(*KamailioAgent).disconnectSession(0xc4205cb920, 0x0, 0x0, 0xc4205377c0, 0x0, 0x0)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/agents/kamagent.go:228 +0xb4
github.com/cgrates/cgrates/agents.(*KamailioAgent).V1DisconnectSession(0xc4205cb920, 0xc4204362a0, 0x1267067, 0xc, 0xc42080f8c0, 0x0, 0x0)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/agents/kamagent.go:250 +0x271
reflect.Value.call(0x11915e0, 0xc4205cb920, 0xe13, 0x125d45d, 0x4, 0xc42065cc80, 0x2, 0x2, 0xc42023e1d0, 0x1037dc0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x11915e0, 0xc4205cb920, 0xe13, 0xc42065cc80, 0x2, 0x2, 0xc4205cb920, 0xe13, 0xc420636420)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/cgrates/cgrates/utils.RPCCall(0x11915e0, 0xc4205cb920, 0x1279cf6, 0x1c, 0x1115600, 0xc4207ff540, 0x1037dc0, 0xc42080f8c0, 0xc4207ff540, 0xc4207ff540)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/utils/coreutils.go:811 +0x2b9
github.com/cgrates/cgrates/agents.(*KamailioAgent).Call(0xc4205cb920, 0x1279cf6, 0x1c, 0x1115600, 0xc4207ff540, 0x1037dc0, 0xc42080f8c0, 0x0, 0xc42065cde8)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/agents/kamagent.go:87 +0x80
github.com/cgrates/cgrates/sessions.(*SessionS).disconnectSession(0xc4204d09a0, 0xc4200114d0, 0x1267067, 0xc, 0x0, 0xc42046b180)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:658 +0x251
github.com/cgrates/cgrates/sessions.(*SessionS).debitLoopSession(0xc4204d09a0, 0xc4200114d0, 0x0, 0x12a05f200, 0x0, 0xc420636480, 0x0)
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:519 +0x44a
created by github.com/cgrates/cgrates/sessions.(*SessionS).initSessionDebitLoops
	/home/darienko.semen/git/tmp/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:1134 +0x156
```
[configuration.zip](https://github.com/cgrates/cgrates/files/2974488/configuration.zip)

**Comment by TeoV** [comment]
Hi sem22,

We tried to reproduce your panic but without success. 
We received this in syslog : 
```
Mar 28 15:33:45 debian CGRateS <CGRKamailio> [17399]: <SessionS> could not complete debit operation on session: <390f834b996f486dc94683d9f73b1c02e627028a>, error: <ACCOUNT_DISABLED>
```
The call stopped, but the engine still running without panic.
Please give us step by step guide on how to reproduce the panic.

Thanks,
TeoV

**Comment by sem32** [comment]
Hi TeoV,
I used kamailio-agent with multiply evapi_conns to different nodes of kamailio and had a panic. 
I think that this is a main problem for panic. As Dan said this feature was added for lab, so issue can be closed.

P.S.: Now I using kamailio-agent in different node and all works correct
Thank you

**Comment by TeoV** [comment]
Hi semn32,

Great ;) 

Thanks,
TeoV
