### ISSUE TITLE
UserS MaxUsage crashing engine when used on ExtraFields

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#164]
Sample API call:

```
 rpc.call("ApierV2.GetMaxUsage",{"TOR":"*sms","Category":"sms","ReqType":"*users","Direction":"*out","Tenant":"*users","Account":"*users","Destination":"3412345","SetupTime":"2014-08-04T13:00:00Z","Usage":"1","ExtraFields":{"Cli":"3433333"}} )
```

Strace:

```
### Started at: Tue Aug 25 17:58:56 EDT 2015
panic: reflect: reflect.Value.SetString using unaddressable value

goroutine 28 [running]:
reflect.flag.mustBeAssignable(0x58)
	/usr/local/go/src/reflect/value.go:222 +0x203
reflect.Value.SetString(0xad4700, 0xc2080f6490, 0x58, 0xc208121b78, 0x8)
	/usr/local/go/src/reflect/value.go:1476 +0x28
github.com/cgrates/cgrates/utils.FromMapStringString(0xc2081179e0, 0xd15f60, 0xc2080f6480)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/utils/struct.go:164 +0x313
github.com/cgrates/cgrates/engine.LoadUserProfile(0xd15f60, 0xc2080f6480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/users.go:460 +0x799
github.com/cgrates/cgrates/apier/v1.(*ApierV1).GetMaxUsage(0xc20806e120, 0xc2080d9730, 0x4, 0xc2080d9728, 0x6, 0xc2080d9724, 0x4, 0xc2080d9790, 0xb, 0xc2080d9720, ...)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/auth.go:31 +0xc9
reflect.Value.call(0xbb1820, 0xd5ee50, 0x13, 0xd84410, 0x4, 0xc2080fff28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xbb1820, 0xd5ee50, 0x13, 0xc2080fff28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080da780, 0xc208035640, 0xc2080d95b8, 0xc208155b00, 0xc20811fba0, 0xd15f60, 0xc2080f6000, 0xd9, 0xa87600, 0xc2080d97b0, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:476 +0x44a
```

**Comment by danbogos** [comment]
@andamasov should be interested about this.
