### ISSUE TITLE
[CRASH] v0.10 when RATING_PLAN_NOT_FOUND

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#2743]
Dear Team,

I am using latest v0.10 and when RatingPlan doens't exist, cgr-engine crashes.

```
/go/bin/cgr-engine --version
CGRateS@v0.10.3~dev-20210219150033-589ee74560cf
```

```
2021/03/15 12:25:56 CGRateS <1> [INFO] LOG Account: {"ID":"voiceland.dev:+302107001397","BalanceMap":{"*monetary":[],"*voice":[{"Uuid":"ba68210f-0136-495c-84ff-64b58174a266","ID":"500MINUTES","Value":29154000000000,"ExpirationDate":"0001-01-01T00:00:00Z","Weight":30,"DestinationIDs":{"*any":true},"RatingSubject":"","Categories":{},"SharedGroups":{},"Timings":null,"TimingIDs":{"*any":true},"Disabled":false,"Factor":null,"Blocker":false}]},"UnitCounters":null,"ActionTriggers":null,"AllowNegative":false,"Disabled":false,"UpdateTime":"2021-03-15T12:24:39.459554279Z"}
2021/03/15 12:25:56 CGRateS <1> [ERROR] Rating plan not found for destination +302107001397 and account: voiceland.dev:9b83b82a-878c-457d-8879-eece6a492994, subject: *out:voiceland.dev:call-in:INTERNAL
2021/03/15 12:25:56 CGRateS <1> [ERROR] <Rater> Error getting cost for account key <voiceland.dev:9b83b82a-878c-457d-8879-eece6a492994>: RATING_PLAN_NOT_FOUND
2021/03/15 12:25:56 CGRateS <1> [ERROR] Rating plan not found for destination +302107001397 and account: voiceland.dev:9b83b82a-878c-457d-8879-eece6a492994, subject: *out:voiceland.dev:call-out:INTERNAL
2021/03/15 12:25:56 CGRateS <1> [ERROR] Rating plan not found for destination +302107001397 and account: voiceland.dev:9b83b82a-878c-457d-8879-eece6a492994, subject: *out:voiceland.dev:call-out:INTERNAL
panic: runtime error: index out of range [0] with length 0
goroutine 187 [running]:
github.com/cgrates/cgrates/engine.(*EventCost).fieldAsInterface(0xc0001494a0, 0xc000de0df0, 0x5, 0x5, 0x0, 0x0, 0x1b27060, 0xc00040edc0)
	/usr/src/cgrates/engine/eventcost.go:938 +0xc88
github.com/cgrates/cgrates/engine.(*EventCost).FieldAsInterface(0xc0001494a0, 0xc000de0df0, 0x5, 0x5, 0xc0001494a0, 0x1, 0xc0005b7870, 0x4526ec)
	/usr/src/cgrates/engine/eventcost.go:917 +0x14a
github.com/cgrates/cgrates/utils.MapStorage.FieldAsInterface(0xc00056b260, 0xc000de0de0, 0x6, 0x6, 0x0, 0x5, 0xc000de0de0, 0x6)
	/usr/src/cgrates/utils/mapstorage.go:96 +0xca4
github.com/cgrates/cgrates/config.(*RSRParser).ParseDataProviderWithInterfaces(0xc0005e3b90, 0x1b4df18, 0xc00056b260, 0x1afe83c, 0x1, 0x456767, 0x0, 0xc0005b79c8, 0x2)
	/usr/src/cgrates/config/rsrparser.go:313 +0xfd
github.com/cgrates/cgrates/engine.(*CDR).FieldAsString(0xc0002e4b40, 0xc0005e3b90, 0x0, 0xc0008cc648, 0x13, 0xc0008cc648)
	/usr/src/cgrates/engine/cdr.go:156 +0x139
github.com/cgrates/cgrates/engine.(*CDR).exportFieldValue(0xc0002e4b40, 0xc0002c1e00, 0xc0002b4b40, 0x9, 0x0, 0x0, 0x0)
	/usr/src/cgrates/engine/cdr.go:339 +0x187
github.com/cgrates/cgrates/engine.(*CDR).formatField(0xc0002e4b40, 0xc0002c1e00, 0x0, 0x0, 0x0, 0x0, 0xc0002b4b40, 0xc00056ab70, 0x1, 0x0, ...)
	/usr/src/cgrates/engine/cdr.go:391 +0x345
github.com/cgrates/cgrates/engine.(*CDR).AsExportMap(0xc0002e4b40, 0xc00010c9c0, 0x19, 0x19, 0x0, 0x0, 0x0, 0x0, 0xc0002b4b40, 0xa0, ...)
	/usr/src/cgrates/engine/cdr.go:455 +0x2b2
github.com/cgrates/cgrates/engine.(*CDRExporter).postCdr(0xc00052f040, 0xc0002e4b40, 0x16ff0ed, 0x4)
	/usr/src/cgrates/engine/cdre.go:252 +0xc68
github.com/cgrates/cgrates/engine.(*CDRExporter).processCDR(0xc00052f040, 0xc0002e4b40, 0x0, 0x0)
	/usr/src/cgrates/engine/cdre.go:339 +0xa74
github.com/cgrates/cgrates/engine.(*CDRExporter).processCDRs.func1(0x0, 0xc0008a4200, 0xc00052f040, 0xc0002e4b40)
	/usr/src/cgrates/engine/cdre.go:406 +0x3c
created by github.com/cgrates/cgrates/engine.(*CDRExporter).processCDRs
	/usr/src/cgrates/engine/cdre.go:405 +0xf5
```

if you want more inside info what is going on using ngrep on port 2012 you can check [here](https://pastebin.com/2pAJ0ymN)

Also cgrates.json is [here](https://pastebin.com/dLK4F7EK)

Let me know if I can provide any more information on this case.

Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Same happens for Destination --> null 

```
2021/03/15 14:00:15 rpc.Register: method "Call" has 4 input parameters; needs exactly three
2021/03/15 14:00:22 CGRateS <1> [INFO] LOG Account: {"ID":"voiceland.dev:+302107001397","BalanceMap":{"*monetary":[],"*voice":[{"Uuid":"ba68210f-0136-495c-84ff-64b58174a266","ID":"500MINUTES","Value":29070000000000,"ExpirationDate":"0001-01-01T00:00:00Z","Weight":30,"DestinationIDs":{"*any":true},"RatingSubject":"","Categories":{},"SharedGroups":{},"Timings":null,"TimingIDs":{"*any":true},"Disabled":false,"Factor":null,"Blocker":false}]},"UnitCounters":null,"ActionTriggers":null,"AllowNegative":false,"Disabled":false,"UpdateTime":"2021-03-15T14:00:04.163677546Z"}
2021/03/15 14:00:22 CGRateS <1> [ERROR] Destination <null> not authorized for account: voiceland.dev:+302107001397, subject: *out:voiceland.dev:*tmp:+302107001397
panic: runtime error: index out of range [0] with length 0

goroutine 238 [running]:
github.com/cgrates/cgrates/engine.(*EventCost).getChargesForPath(0xc00044a8c0, 0xc000c6e9e0, 0x4, 0x4, 0xc000980c80, 0x1051300, 0xc000038705, 0xc000861360, 0x16ccea8)
	/usr/src/cgrates/engine/eventcost.go:1030 +0x57a
github.com/cgrates/cgrates/engine.(*EventCost).fieldAsInterface(0xc00044a8c0, 0xc000c6e9d0, 0x5, 0x5, 0x0, 0x0, 0x1b27060, 0xc0003c2e50)
	/usr/src/cgrates/engine/eventcost.go:938 +0x23f
github.com/cgrates/cgrates/engine.(*EventCost).FieldAsInterface(0xc00044a8c0, 0xc000c6e9d0, 0x5, 0x5, 0xc00044a8c0, 0x1, 0xc0002af870, 0x4526ec)
	/usr/src/cgrates/engine/eventcost.go:917 +0x14a
github.com/cgrates/cgrates/utils.MapStorage.FieldAsInterface(0xc000cf2900, 0xc000c6e9c0, 0x6, 0x6, 0x0, 0x5, 0xc000c6e9c0, 0x6)
	/usr/src/cgrates/utils/mapstorage.go:96 +0xca4
github.com/cgrates/cgrates/config.(*RSRParser).ParseDataProviderWithInterfaces(0xc0005c1a40, 0x1b4df18, 0xc000cf2900, 0x1afe83c, 0x1, 0x456767, 0x0, 0xc0002af9c8, 0x2)
	/usr/src/cgrates/config/rsrparser.go:313 +0xfd
github.com/cgrates/cgrates/engine.(*CDR).FieldAsString(0xc00025a8c0, 0xc0005c1a40, 0x0, 0xc000815668, 0x13, 0xc000815668)
	/usr/src/cgrates/engine/cdr.go:156 +0x139
github.com/cgrates/cgrates/engine.(*CDR).exportFieldValue(0xc00025a8c0, 0xc000251e00, 0xc00020ca38, 0x9, 0x0, 0x0, 0x0)
	/usr/src/cgrates/engine/cdr.go:339 +0x187
github.com/cgrates/cgrates/engine.(*CDR).formatField(0xc00025a8c0, 0xc000251e00, 0x0, 0x0, 0x0, 0x0, 0xc00020ca38, 0xc000cf2210, 0x1, 0x0, ...)
	/usr/src/cgrates/engine/cdr.go:391 +0x345
github.com/cgrates/cgrates/engine.(*CDR).AsExportMap(0xc00025a8c0, 0xc00046a750, 0x19, 0x19, 0x0, 0x0, 0x0, 0x0, 0xc00020ca38, 0xa0, ...)
	/usr/src/cgrates/engine/cdr.go:455 +0x2b2
github.com/cgrates/cgrates/engine.(*CDRExporter).postCdr(0xc000193520, 0xc00025a8c0, 0x16ff0ed, 0x4)
	/usr/src/cgrates/engine/cdre.go:252 +0xc68
github.com/cgrates/cgrates/engine.(*CDRExporter).processCDR(0xc000193520, 0xc00025a8c0, 0x0, 0x0)
	/usr/src/cgrates/engine/cdre.go:339 +0xa74
github.com/cgrates/cgrates/engine.(*CDRExporter).processCDRs.func1(0x0, 0xc00084c860, 0xc000193520, 0xc00025a8c0)
	/usr/src/cgrates/engine/cdre.go:406 +0x3c
created by github.com/cgrates/cgrates/engine.(*CDRExporter).processCDRs
	/usr/src/cgrates/engine/cdre.go:405 +0xf5
```

thank you in advance

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
its working thanks @Trial97 @danbogos  !!!
