### ISSUE TITLE
[CRASH] v0.10 when on call and CGRateS Engine restarts

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#2764]
Dear Team,

CGRateS v0.10 

```
/go/bin/cgr-engine --version
CGRateS@v0.10.3~dev-20210319074531-bc08d94fae4a
```

Crashes with 
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x1051177]`

when there is an on going call and I manually restart CGRateS Engine and then I hangup the call.
This happens 3-4 seconds after the call hangup.

Logs:

```
goroutine 187 [running]:
github.com/cgrates/cgrates/engine.(*EventCost).FieldAsInterface(0x0, 0xc00013ba50, 0x5, 0x5, 0x0, 0x1, 0xc00097b870, 0x4526ec)
	/usr/src/cgrates/engine/eventcost.go:907 +0x37
github.com/cgrates/cgrates/utils.MapStorage.FieldAsInterface(0xc000565140, 0xc00013ba40, 0x6, 0x6, 0x0, 0x5, 0xc00013ba40, 0x6)
	/usr/src/cgrates/utils/mapstorage.go:95 +0xca4
github.com/cgrates/cgrates/config.(*RSRParser).ParseDataProviderWithInterfaces(0xc0005d9b90, 0x1b4df98, 0xc000565140, 0x1afe8bc, 0x1, 0x456767, 0x0, 0xc00097b9c8, 0x2)
	/usr/src/cgrates/config/rsrparser.go:313 +0xfd
github.com/cgrates/cgrates/engine.(*CDR).FieldAsString(0xc000484dc0, 0xc0005d9b90, 0x0, 0xc00082b9f8, 0x13, 0xc00082b9f8)
	/usr/src/cgrates/engine/cdr.go:156 +0x139
github.com/cgrates/cgrates/engine.(*CDR).exportFieldValue(0xc000484dc0, 0xc000344000, 0xc0002f4c30, 0x9, 0x0, 0x0, 0x0)
	/usr/src/cgrates/engine/cdr.go:339 +0x187
github.com/cgrates/cgrates/engine.(*CDR).formatField(0xc000484dc0, 0xc000344000, 0x0, 0x0, 0x0, 0x0, 0xc0002f4c30, 0xc000564930, 0x1, 0x0, ...)
	/usr/src/cgrates/engine/cdr.go:391 +0x345
github.com/cgrates/cgrates/engine.(*CDR).AsExportMap(0xc000484dc0, 0xc00022f790, 0x1a, 0x1a, 0x75be00, 0x0, 0x0, 0x0, 0xc0002f4c30, 0x23bf8e0, ...)
	/usr/src/cgrates/engine/cdr.go:455 +0x2b2
github.com/cgrates/cgrates/engine.(*CDRExporter).postCdr(0xc000754d00, 0xc000484dc0, 0x16ff12d, 0x4)
	/usr/src/cgrates/engine/cdre.go:252 +0xc68
github.com/cgrates/cgrates/engine.(*CDRExporter).processCDR(0xc000754d00, 0xc000484dc0, 0x0, 0x0)
	/usr/src/cgrates/engine/cdre.go:339 +0xa74
github.com/cgrates/cgrates/engine.(*CDRExporter).processCDRs.func1(0x0, 0xc0004c97f0, 0xc000754d00, 0xc000484dc0)
	/usr/src/cgrates/engine/cdre.go:406 +0x3c
created by github.com/cgrates/cgrates/engine.(*CDRExporter).processCDRs
	/usr/src/cgrates/engine/cdre.go:405 +0xf5
```

cgrates.json --> [here](https://pastebin.com/XjyvUjF3)

Let me know if you need any further information on this case

Thank you in advance for your support

Vasilios Tzanoudakis

**Comment by Jajcus** [comment]
Any chance to get this into a released v0.10 version?

**Comment by danbogos** [comment]
We have pushed a new development package on v0.10. Hope that will do.

DanB

**Comment by vtzan** [comment]
@danbogos I have just tested that. Its working great!!! thanks !!!
