### ISSUE TITLE
[CRASH] v0.10 when sending RALsV1Ping

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#2779]
Dear Team,

While investigating https://github.com/cgrates/cgrates/issues/2776
I came across with this crash.

Reproduce:
1) start CGRateS with cgrates.json config [here](https://pastebin.com/GDskRHh8)
2) send the below request
```
{
    "method": "RALsV1.Ping",
    "params": [
        {}
    ],
    "id": 0
}
```

**logs:**
```
bash-5.1# /go/bin/cgr-engine
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting version <CGRateS@v0.10.3~dev-20210323112613-d58e231beb5b><go1.16.2>
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <CDRs> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] Starting CGRateS Dispatcher service.
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <AttributeS> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <ResourceS> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <ApierS> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <SupplierS> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <ChargerS> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <ThresholdS> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] Registering CDRS HTTP Handlers.
2021/03/29 13:24:12 CGRateS <1> [INFO] Registering CDRS RPC service.
2021/03/29 13:24:12 CGRateS <1> [INFO] <CoreS> starting <Stats> subsystem
2021/03/29 13:24:12 CGRateS <1> [INFO] <ServiceManager> Starting CGRateS Scheduler.
2021/03/29 13:24:12 CGRateS <1> [WARNING] WARNING: missing TLS certificate/key file!
2021/03/29 13:24:12 CGRateS <1> [WARNING] WARNING: missing TLS certificate/key file!
2021/03/29 13:24:12 CGRateS <1> [WARNING] WARNING: missing TLS certificate/key file!
2021/03/29 13:24:12 CGRateS <1> [INFO] <HTTP> enabling handler for JSON-RPC
2021/03/29 13:24:12 CGRateS <1> [INFO] <HTTP> enabling handler for WebSocket connections
2021/03/29 13:24:12 CGRateS <1> [INFO] <HTTP> start listening at <:2080>
2021/03/29 13:24:12 CGRateS <1> [INFO] Starting CGRateS JSON server at <:2012>.
2021/03/29 13:24:12 CGRateS <1> [INFO] Starting CGRateS GOB server at <:2013>.
2021/03/29 13:24:12 CGRateS <1> [INFO] <Scheduler> processing 8 action plans
2021/03/29 13:24:12 CGRateS <1> [INFO] <Scheduler> queued 0 action plans
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11dc4e6]

goroutine 102 [running]:
github.com/cgrates/cgrates/dispatchers.(*DispatcherService).RALsV1Ping(0xc000130860, 0xc0004b8ae0, 0xc0004b8b80, 0x7f43730515b8, 0x30)
	/usr/src/cgrates/dispatchers/rals.go:29 +0x86
github.com/cgrates/cgrates/apier/v1.(*DispatcherRALsV1).Ping(0xc000011f68, 0xc0004b8ae0, 0xc0004b8b80, 0x0, 0x0)
	/usr/src/cgrates/apier/v1/dispatcher.go:811 +0x45
reflect.Value.call(0xc0001f3c80, 0xc000011fa8, 0x13, 0x16ff1ad, 0x4, 0xc000066f08, 0x3, 0x3, 0xc0003a0cc0, 0x37, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0001f3c80, 0xc000011fa8, 0x13, 0xc0008a0708, 0x3, 0x3, 0xc0003a0cc0, 0x37, 0x0)
	/usr/local/go/src/reflect/value.go:337 +0xb9
net/rpc.(*service).call(0xc0001ca640, 0xc000088190, 0xc00013c5b0, 0xc00013c5c0, 0xc000405e00, 0xc0001463e0, 0x161da20, 0xc0004b8ae0, 0x16, 0x144ecc0, ...)
	/usr/local/go/src/net/rpc/server.go:377 +0x189
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:474 +0x44d
```

Thank you in advance for your support
Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
Hello @vtzan 

Thank you for this notice. Fixed in this commit
https://github.com/porosnicuadrian/cgrates/commit/adeca9e9882814a12ce635c3bef0a2407daf0356

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Its working great! thank you for your support!
