### ISSUE TITLE
Cgrates is crashing on Opensips 3.1 shutdown

### ISSUE THREAD

**Issue by mikewillmars** [cgrates/cgrates#3580]
Hello, I have some issue when stopping opensips instance, almost everytime CgrateS crashes.

I posted earlier on google groups: https://groups.google.com/g/cgrates/c/BAPWF4373aU

I tried with recent versions of Cgrates v0.11.0~dev-20220206130914-4d9c9d248a8b & Opensips 3.1 (git rev. 2ff20721a) in a staged evironment and problem still exists.

**CgrateS logs**
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13107ee]
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: goroutine 157 [running]:
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: github.com/cgrates/cgrates/analyzers.(*AnalyzerBiRPCCodec).ReadHeader(0xc00080ad20, 0xc00084c540, 0xc00084c570)
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: #011/home/dan/go/src/github.com/cgrates/cgrates/analyzers/codec.go:130 +0x18e
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: github.com/cenkalti/rpc2.(*Client).readLoop(0xc00034a770)
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: #011/home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2/client.go:87 +0x11b
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: github.com/cenkalti/rpc2.(*Client).Run(...)
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: #011/home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2/client.go:62
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: github.com/cenkalti/rpc2.(*Server).ServeCodecWithState(0xc000b7ad10, {0x22efbf0, 0xc00080ad20}, 0xc000455b80)
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: #011/home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2/server.go:179 +0x1b0
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: github.com/cenkalti/rpc2.(*Server).ServeCodec(0xc000825fd0, {0x22efbf0, 0xc00080ad20})
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: #011/home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2/server.go:164 +0x70
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: created by github.com/cgrates/cgrates/cores.(*Server).acceptBiRPC
Feb 14 20:49:12 cgrates-dev cgr-engine[184193]: #011/home/dan/go/src/github.com/cgrates/cgrates/cores/server.go:300 +0x59
Feb 14 20:49:13 cgrates-dev CGRateS <25b5f1b> [184240]: <CoreS> starting version <CGRateS@v0.11.0~dev-20220206130914-4d9c9d248a8b><go1.17.5>
Feb 14 20:49:13 cgrates-dev CGRateS <25b5f1b> [184240]: <CoreS> starting <CoreS> subsystem
Feb 14 20:49:13 cgrates-dev CGRateS <25b5f1b> [184240]: <CoreS> starting <AnalyzerS> subsystem

**Opensips logs**

root@proxy01-dev:~# /usr/local/opensips/sbin/opensips -V
version: opensips 3.1.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 2ff20721a
main.c compiled on 18:46:43 Feb 14 2022 with gcc 10

Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42104]: INFO:core:sig_usr: signal 15 received
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42103]: INFO:core:sig_usr: signal 15 received
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42106]: INFO:core:sig_usr: signal 15 received
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42133]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42133]: INFO:cgrates:cgrc_close: closing connection 172.20.0.140:2014
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42105]: INFO:core:sig_usr: signal 15 received
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42132]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42132]: INFO:cgrates:cgrc_close: closing connection 172.20.0.140:2014
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42131]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42131]: INFO:cgrates:cgrc_close: closing connection 172.20.0.140:2014
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42130]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Feb 14 20:49:12 proxy01-dev /usr/local/opensips/sbin/opensips[42130]: INFO:cgrates:cgrc_close: closing connection 172.20.0.140:2014

**Comment by mikewillmars** [comment]
Hello, I would like to add, that I stopped having this issue after I edited **/etc/cgrates/cgrates.json** so that analayzers no longer is enabled... 

```
"analyzers": {
        "enabled": false
}
```

I guess it's not a real issue, just a configuration error .. :)
