### ISSUE TITLE
CGrates crashing (Package 14th March 2016)

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#403]
Hi DanB,

We see that CGRateS is crashing at least twice daily on some systems, see the strace of the last crash below.

We are doing CDR Replication not storing CDRs in StorDB.

root@cgrtbill:/var/run/cgrates# ls -l /usr/bin | grep cgr
-rwxr-xr-x 1 root   root    13925696 Mar 14 01:52 cgr-console
-rwxr-xr-x 1 root   root    18254976 Mar 14 01:52 cgr-engine
-rwxr-xr-x 1 root   root    15162944 Mar 14 01:52 cgr-loader
-rwxr-xr-x 1 root   root    14224928 Mar 14 01:52 cgr-tester

root@# cat /etc/debian_version
7.9

****** Begin strace ********

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:40:22]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:44:38]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:44:38]  
^C
root@cgrtbill:/var/run/cgrates# tail -100 cgrates.strace 
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 580961 [chan send]:
github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr.func1(0xc820494070, 0xc86c0ba680, 0xf18580, 0xc887e83920, 0xc82011be50, 0x1011590, 0x4, 0xc8448d4900)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:445 +0x433
created by github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:447 +0x2f6

goroutine 580979 [IO wait]:
net.runtime_pollWait(0x7fcda5ec36c0, 0x72, 0xc884539000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc86fdb5790, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc86fdb5790, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc86fdb5730, 0xc884539000, 0x1000, 0x1000, 0x0, 0x7fcdaaae9050, 0xc82000a130)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc84332f798, 0xc884539000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fcda8aac680, 0xc84332f798, 0xc82ece83a8, 0xc884539000, 0x1000, 0x1000, 0x4165e3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc824e70740, 0xc884539000, 0x1000, 0x1000, 0xc866aead1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8448d4d20)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8448d4d20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82ece8340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 580980 [select]:
net/http.(*persistConn).writeLoop(0xc82ece8340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

### Started at: Mon Mar 21 08:57:53 PDT 2016

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:00:30]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:00:30]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:05:48]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:05:48]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:08:53]  

(pq: duplicate key value violates unique constraint "cost_details_cgrid_runid_key") 
[2016-03-21 09:08:53]  
.
.
.
************** End Strace ***************

Any ideas?

Regards,

Errol

**Comment by ewsamuels** [comment]
Updated to March 22nd package.  No crashes noted as yet.
