### ISSUE TITLE
Cdrc exception

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#60]
Hi, 

I've just update to the last master version, and I can't get the CDRC working as the commit: bf27fa351236e906daf53947bd695ff2e3996041

I updated the config, but when a new csv is processed looks like that cdrServer doesn't have attribute *rater*

Could you help me? Any idea?

Here you have the config: 
```js
{
    "general": {
        "http_skip_tls_veify": false,
        "rounding_decimals": 10,
        "dbdata_encoding": "msgpack",
        "tpexport_dir": "/var/log/cgrates/tpe",
        "default_reqtype": "*rated",
        "default_category": "call",
        "default_tenant": "cgrates.org",
        "default_subject": "cgrates"
    },

    "listen": {
        "rpc_json": "127.0.0.1:2012",
        "rpc_gob": "127.0.0.1:2013",
        "http": "127.0.0.1:2080"
    },

    "rating_db": {
        "db_type": "redis",
        "db_host": "127.0.0.1",
        "db_port": 6379,
        "db_name": "10",
        "db_user": "",
        "db_passwd": ""
    },

    "accounting_db": {
        "db_type": "redis",
        "db_host": "127.0.0.1",
        "db_port": 6379,
        "db_name": "11",
        "db_user": "",
        "db_passwd": ""
    },


    "stor_db": {
        "db_type": "mysql",
        "db_host": "127.0.0.1",
        "db_port": 3306,
        "db_name": "cgrates_new",
        "db_user": "test",
        "db_passwd": "test",
        "max_open_conns": 0,
        "max_idle_conns": -1
    },

    "balancer": {
      "enabled": true
    },

    "rater": {
      "enabled": true
    },

    "scheduler": {
        "enabled": true
    },

    "cdrs": {
        "enabled": true,
        "extra_fields": [],
        "rate_cdrs": true,
        "store_cdrs": true,
        "rater": "internal",
        "cdrstats": "",
        "reconnects": 5,
        "cdr_replication":[]
    },

    "mediator": {
        "enabled": true,
        "reconnects": 3,
        "rater": "internal",
        "cdrstats": "",
        "store_disable": false
    },

    "cdrc": {
      "*default": {
          "enabled": true,
          "cdrs": "internal",
          "cdr_format": "csv",
          "field_separator": ",",
          "run_delay": 0,
          "data_usage_multiply_factor": 1024,
          "cdr_in_dir": "/var/log/cgrates/cdrc/in",
          "cdr_out_dir": "/var/log/cgrates/cdrc/out",
          "cdr_source_id": "freeswitch_csv",
          "cdr_filter": "",
          "cdr_fields":[
              {"tag": "tor", "cdr_field_id": "tor", "type": "cdrfield", "value": "0", "mandatory": true},
              {"tag": "accid", "cdr_field_id": "accid", "type": "cdrfield", "value": "1", "mandatory": true},
              {"tag": "reqtype", "cdr_field_id": "reqtype", "type": "cdrfield", "value": "2", "mandatory": true},
              {"tag": "direction", "cdr_field_id": "direction", "type": "cdrfield", "value": "3", "mandatory": true},
              {"tag": "tenant", "cdr_field_id": "tenant", "type": "cdrfield", "value": "4", "mandatory": true},
              {"tag": "category", "cdr_field_id": "category", "type": "cdrfield", "value": "5", "mandatory": true},
              {"tag": "account", "cdr_field_id": "account", "type": "cdrfield", "value": "6", "mandatory": true},
              {"tag": "subject", "cdr_field_id": "subject", "type": "cdrfield", "value": "7", "mandatory": true},
              {"tag": "destination", "cdr_field_id": "destination", "type": "cdrfield", "value": "8", "mandatory": true},
              {"tag": "setup_time", "cdr_field_id": "setup_time", "type": "cdrfield", "value": "9", "mandatory": true},
              {"tag": "answer_time", "cdr_field_id": "answer_time", "type": "cdrfield", "value": "10", "mandatory": true},
              {"tag": "usage", "cdr_field_id": "usage", "type": "cdrfield", "value": "12", "mandatory": true}
          ]
      }
    }
}
```

And here the coredump: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5172ea]

goroutine 21 [running]:
github.com/cgrates/cgrates/engine.(*CdrServer).rateStoreStatsReplicate(0x0, 0xc2080fe480, 0x0, 0x0)
        /root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:133 +0xea
github.com/cgrates/cgrates/engine.(*CdrServer).ProcessCdr(0x0, 0xc2080fe480, 0x0, 0x0)
        /root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:90 +0x44
github.com/cgrates/cgrates/cdrc.(*Cdrc).processFile(0xc20809e0c0, 0xc2080e4dc0, 0x37, 0x0, 0x0)
        /root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:245 +0xd9e
github.com/cgrates/cgrates/cdrc.funcÂ¬âˆ‘001()
        /root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:167 +0x5e
created by github.com/cgrates/cgrates/cdrc.(*Cdrc).trackCDRFiles
        /root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:170 +0x745

goroutine 1 [chan receive]:
main.main()
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:646 +0x1b1a

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.initÂ¬âˆ‘1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan send]:
github.com/cgrates/cgrates/balancer2go.funcÂ¬âˆ‘001()
        /root/.go/src/github.com/cgrates/cgrates/balancer2go/balancer.go:31 +0x15f
created by github.com/cgrates/cgrates/balancer2go.NewBalancer
        /root/.go/src/github.com/cgrates/cgrates/balancer2go/balancer.go:34 +0x15b

goroutine 8 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208113540)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc2080f9950, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080f9950, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080f98f0, 0x0, 0x7facca74df70, 0xc20800b3b0)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080383c8, 0x6, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080383c8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/cgrates/cgrates/engine.(*Server).ServeJSON(0x118d04a, 0xc208076b60, 0xe)
        /root/.go/src/github.com/cgrates/cgrates/engine/server.go:63 +0x326
created by main.serveRpc
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:371 +0xcc

goroutine 10 [chan receive]:
main.generalSignalHandler()
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:49 +0x25b
created by main.main
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:577 +0x12b2

goroutine 11 [chan receive]:
github.com/cgrates/cgrates/scheduler.(*Scheduler).Loop(0xc20811e210)
        /root/.go/src/github.com/cgrates/cgrates/scheduler/scheduler.go:44 +0x61
main.funcÂ¬âˆ‘001()
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:588 +0x154
created by main.main
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:589 +0x13c2

goroutine 17 [syscall]:
syscall.Syscall(0x0, 0x7, 0xc20818bee0, 0x10000, 0x414a75, 0xc208001b00, 0xc2080e4e40)
        /usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x7, 0xc20818bee0, 0x10000, 0x10000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x7, 0xc20818bee0, 0x10000, 0x10000, 0xc20805f05c, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:136 +0x58
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208095320)
        /root/.go/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0x12c
created by github.com/howeyc/fsnotify.NewWatcher
        /root/.go/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x420

goroutine 13 [select]:
github.com/cgrates/cgrates/cdrc.(*Cdrc).trackCDRFiles(0xc20809e0c0, 0x0, 0x0)
        /root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:159 +0x93a
github.com/cgrates/cgrates/cdrc.(*Cdrc).Run(0xc20809e0c0, 0x0, 0x0)
        /root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:130 +0x50
main.startCdrc(0xc208095020, 0xc2080d1950, 0xd2f400, 0x0, 0xc208094f00)
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:107 +0x2e7
created by main.main
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:637 +0x1cf1

goroutine 15 [IO wait]:
net.(*pollDesc).Wait(0xc2080f9090, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080f9090, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080f9030, 0x0, 0x7facca74df70, 0xc208077a48)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038368, 0x6c87f4, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208038368, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208095380, 0x7facca7506d8, 0xc208038368, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208095380, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc208076ba0, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1808 +0xba
github.com/cgrates/cgrates/engine.(*Server).ServeHTTP(0x118d04a, 0xc208076ba0, 0xe)
        /root/.go/src/github.com/cgrates/cgrates/engine/server.go:113 +0x22c
main.serveHttp(0xc208038340, 0x1, 0x1)
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:380 +0xc2
created by main.main
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:645 +0x1af3

goroutine 16 [chan receive]:
main.reloadSchedulerSingnalHandler(0xc20811e210, 0x7facca74ff68, 0xc208050360)
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:111 +0x172
created by main.funcÂ¬âˆ‘001
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:584 +0xd7

goroutine 18 [runnable]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208095320)
        /root/.go/src/github.com/howeyc/fsnotify/fsnotify.go:44 +0x222
created by github.com/howeyc/fsnotify.NewWatcher
        /root/.go/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x43a

goroutine 20 [IO wait]:
net.(*pollDesc).Wait(0xc2080f9a30, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080f9a30, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080f99d0, 0x0, 0x7facca74df70, 0xc20800b460)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080383d0, 0x6, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080383d0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/cgrates/cgrates/engine.(*Server).ServeGOB(0x118d04a, 0xc208076b80, 0xe)
        /root/.go/src/github.com/cgrates/cgrates/engine/server.go:85 +0x326
created by main.serveRpc
        /root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:372 +0x108
```

**Comment by danbogos** [comment]
Hey @eloycoto,

Any chance you send me a sample of cdr file you are trying to import, together with your config file? It appears that there is no CDR being sent to CDRS, I don't think it has anything to do with rater there.

Thanks,
DanB

PS: You can remove mediator section from your config since that is not longer in use.

**Comment by danbogos** [comment]
@eloycoto, thanks for the comprehensive information. Please retry with latest master, should be fixed now.

DanB
