### ISSUE TITLE
Cdrc exception

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#61]
Hi, 

I'm having trouble with the cdrc, I got this exception and I don't know why. Some files work ok, but sometimes I have this coredump.  Any idea?

Cdr-file:
```
01d45d58-ea58-11e4-a27b-005056a9041e,foehn,0034678096720,*out,postpaid,2015-04-24 07:59:04,2015-04-24 07:59:11,176,foehn,*voice
```

Config: 
```js
{
    "general": {
        "http_skip_tls_veify": false,
        "rounding_decimals": 10,
        "dbdata_encoding": "msgpack",
        "tpexport_dir": "/var/log/cgrates/tpe",
        "default_reqtype": "*rated",
        "default_category": "call",
        "default_tenant": "cgrates.org",
        "default_subject": "cgrates"
    },

    "listen": {
        "rpc_json": "127.0.0.1:2012",
        "rpc_gob": "127.0.0.1:2013",
        "http": "127.0.0.1:2080"
    },

    "rating_db": {
        "db_type": "redis",
        "db_host": "127.0.0.1",
        "db_port": 6379,
        "db_name": "10",
        "db_user": "",
        "db_passwd": ""
    },

    "accounting_db": {
        "db_type": "redis",
        "db_host": "127.0.0.1",
        "db_port": 6379,
        "db_name": "11",
        "db_user": "",
        "db_passwd": ""
    },


    "stor_db": {
        "db_type": "mysql",
        "db_host": "127.0.0.1",
        "db_port": 3306,
        "db_name": "cgrates",
        "db_user": "xxxx",
        "db_passwd": "xxxx",
        "max_open_conns": 0,
        "max_idle_conns": -1
    },

    "balancer": {
      "enabled": false
    },

    "rater": {
      "enabled": true
    },

    "scheduler": {
        "enabled": true
    },

    "cdrs": {
        "enabled": true,
        "extra_fields": [],
        "rate_cdrs": true,
        "store_cdrs": true,
        "rater": "internal",
        "cdrstats": "",
        "reconnects": 5,
        "cdr_replication":[]
    },

    "cdr_stats": {
        "enabled": true,
        "queue_length": 100000,
        "time_window": "24h",
        "metrics": ["ASR", "ACD", "ACC", "TCC"],
        "setup_interval": [],
        "tors": [],
        "cdr_hosts": [],
        "cdr_sources": [],
        "req_types": [],
        "directions": [],
        "tenants": [],
        "categories": [],
        "accounts": [],
        "subjects": [],
        "destination_prefixes": [],
        "usage_interval": [],
        "mediation_run_ids": [],
        "rated_accounts": [],
        "rated_subjects": [],
        "cost_interval": [],
    },

    "cdrc": {
      "*default": {
          "enabled": true,
          "cdrs": "internal",
          "cdr_format": "csv",
          "field_separator": ",",
          "run_delay": 0,
          "data_usage_multiply_factor": 1024,
          "cdr_in_dir": "/var/log/cgrates/cdrc/in",
          "cdr_out_dir": "/var/log/cgrates/cdrc/out",
          "cdr_source_id": "freeswitch_csv",
          "cdr_filter": "",
          "cdr_fields":[
              {"tag": "tor", "cdr_field_id": "tor", "type": "cdrfield", "value": "9", "mandatory": true},
              {"tag": "accid", "cdr_field_id": "accid", "type": "cdrfield", "value": "0", "mandatory": true},
              {"tag": "reqtype", "cdr_field_id": "reqtype", "type": "cdrfield", "value": "4", "mandatory": true},
              {"tag": "direction", "cdr_field_id": "direction", "type": "cdrfield", "value": "3", "mandatory": true},
              {"tag": "tenant", "cdr_field_id": "tenant", "type": "cdrfield", "value": "8", "mandatory": true},
              {"tag": "category", "cdr_field_id": "category", "type": "cdrfield", "value": "4", "mandatory": true},
              {"tag": "account", "cdr_field_id": "account", "type": "cdrfield", "value": "1", "mandatory": true},
              {"tag": "subject", "cdr_field_id": "subject", "type": "cdrfield", "value": "1", "mandatory": true},
              {"tag": "destination", "cdr_field_id": "destination", "type": "cdrfield", "value": "2", "mandatory": true},
              {"tag": "setup_time", "cdr_field_id": "setup_time", "type": "cdrfield", "value": "5", "mandatory": true},
              {"tag": "answer_time", "cdr_field_id": "answer_time", "type": "cdrfield", "value": "6", "mandatory": true},
              {"tag": "usage", "cdr_field_id": "usage", "type": "cdrfield", "value": "7", "mandatory": true}
          ]
      }
    }
}
```

Account info: 
```
{
 "Id": "*out:foehn:foehn",
 "BalanceMap": {
  "*monetary*out": [
   {
    "Uuid": "166dbd234078ab528070d23bbf9a567d",
    "Value": 1510,
    "ExpirationDate": "0001-01-01T00:00:00Z",
    "Weight": 10,
    "DestinationId": "*any",
    "RatingSubject": "",
    "SharedGroup": ""
   },
   {
    "Uuid": "",
    "Value": 1687.3219424981,
    "ExpirationDate": "0001-01-01T00:00:00Z",
    "Weight": 0,
    "DestinationId": "*any",
    "RatingSubject": "",
    "SharedGroup": ""
   }
  ]
 },
 "UnitCounters": [
  {
   "Direction": "*out",
   "BalanceType": "*monetary",
   "Balances": [
    {
     "Uuid": "",
     "Value": 0,
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationId": "",
     "RatingSubject": "",
     "SharedGroup": ""
    }
   ]
  }
 ],
 "ActionTriggers": [
  {
   "Id": "2d6b52df-bfa1-45e7-b7f3-206651455b4e",
   "BalanceType": "*monetary",
   "Direction": "",
   "ThresholdType": "*min_balance",
   "ThresholdValue": 2,
   "Recurrent": false,
   "MinSleep": 0,
   "DestinationId": "",
   "BalanceWeight": 0,
   "BalanceExpirationDate": "0001-01-01T00:00:00Z",
   "BalanceRatingSubject": "",
   "BalanceSharedGroup": "",
   "Weight": 10,
   "ActionsId": "LOG_WARNING",
   "MinQueuedItems": 0,
   "Executed": false
  }
 ],
 "AllowNegative": false,
 "Disabled": false
}

```

Coredump:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x5098c9]

goroutine 21 [running]:
github.com/cgrates/cgrates/engine.(*Balance).DebitMoney(0xc208581790, 0xc2080ad680, 0xc209476910, 0xc209400001, 0xc209498500, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/balances.go:423 +0x2d9
github.com/cgrates/cgrates/engine.(*Account).debitCreditBalance(0xc209476910, 0xc2080ad680, 0x10001, 0xc209498320, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/account.go:275 +0x713
github.com/cgrates/cgrates/engine.(*CallDescriptor).debit(0xc2080ad680, 0xc209476910, 0x100, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/calldesc.go:525 +0x130
github.com/cgrates/cgrates/engine.func¬∑007(0x0, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/calldesc.go:554 +0x76
github.com/cgrates/cgrates/engine.(*AccountLock).Guard(0x117f600, 0xc2094334f8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/accountlock.go:44 +0x219
github.com/cgrates/cgrates/engine.(*CallDescriptor).Debit(0xc2080ad680, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/calldesc.go:556 +0x163
github.com/cgrates/cgrates/engine.(*Responder).Debit(0xc20811f440, 0xc209404e60, 0x4, 0xc209404e68, 0x8, 0xc209404e73, 0x5, 0xc209404e18, 0x5, 0xc209404e18, ...)
	/root/.go/src/github.com/cgrates/cgrates/engine/responder.go:75 +0x113
github.com/cgrates/cgrates/engine.(*CdrServer).getCostFromRater(0xc20939aff0, 0xc209250180, 0x2, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:220 +0x30a
github.com/cgrates/cgrates/engine.(*CdrServer).rateCDR(0xc20939aff0, 0xc209250180, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:288 +0x1d2
github.com/cgrates/cgrates/engine.(*CdrServer).deriveAndRateCdr(0xc20939aff0, 0xc209250180, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:180 +0x169
github.com/cgrates/cgrates/engine.(*CdrServer).rateStoreStatsReplicate(0xc20939aff0, 0xc209250180, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:134 +0x11a
github.com/cgrates/cgrates/engine.(*CdrServer).ProcessCdr(0xc20939aff0, 0xc209250180, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/engine/cdrs.go:90 +0x44
github.com/cgrates/cgrates/cdrc.(*Cdrc).processFile(0xc209244f00, 0xc2093db5c0, 0x21, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:245 +0xd9e
github.com/cgrates/cgrates/cdrc.func¬∑001()
	/root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:167 +0x5e
created by github.com/cgrates/cgrates/cdrc.(*Cdrc).trackCDRFiles
	/root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:170 +0x745

goroutine 1 [chan receive]:
main.main()
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:646 +0x1b0e

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init¬∑1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan send]:
github.com/cgrates/cgrates/balancer2go.func¬∑001()
	/root/.go/src/github.com/cgrates/cgrates/balancer2go/balancer.go:31 +0x15f
created by github.com/cgrates/cgrates/balancer2go.NewBalancer
	/root/.go/src/github.com/cgrates/cgrates/balancer2go/balancer.go:34 +0x15b

goroutine 8 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208111180)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc2093f6990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2093f6990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2093f6930, 0x0, 0x7fce11a12f70, 0xc209404cb8)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2081ffb18, 0x6, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2081ffb18, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/cgrates/cgrates/engine.(*Server).ServeGOB(0x118b06a, 0xc208074ba0, 0xe)
	/root/.go/src/github.com/cgrates/cgrates/engine/server.go:85 +0x326
created by main.serveRpc
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:372 +0x108

goroutine 10 [chan receive]:
main.generalSignalHandler()
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:49 +0x25b
created by main.main
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:577 +0x12b2

goroutine 11 [chan receive]:
github.com/cgrates/cgrates/scheduler.(*Scheduler).Loop(0xc20811f980)
	/root/.go/src/github.com/cgrates/cgrates/scheduler/scheduler.go:44 +0x61
main.func¬∑001()
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:588 +0x154
created by main.main
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:589 +0x13c2

goroutine 12 [chan receive]:
main.reloadSchedulerSingnalHandler(0xc20811f980, 0x7fce11a14f80, 0xc208050c60)
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:111 +0x172
created by main.func¬∑001
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:584 +0xd7

goroutine 17 [IO wait]:
net.(*pollDesc).Wait(0xc2093f6920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2093f6920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2093f68c0, 0x0, 0x7fce11a12f70, 0xc209404c08)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2081ffb08, 0x6, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2081ffb08, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/cgrates/cgrates/engine.(*Server).ServeJSON(0x118b06a, 0xc208074b80, 0xe)
	/root/.go/src/github.com/cgrates/cgrates/engine/server.go:63 +0x326
created by main.serveRpc
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:371 +0xcc

goroutine 14 [select]:
github.com/cgrates/cgrates/cdrc.(*Cdrc).trackCDRFiles(0xc209244f00, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:159 +0x93a
github.com/cgrates/cgrates/cdrc.(*Cdrc).Run(0xc209244f00, 0x0, 0x0)
	/root/.go/src/github.com/cgrates/cgrates/cdrc/cdrc.go:130 +0x50
main.startCdrc(0xc208095c80, 0xc2080d9950, 0xd2d000, 0xc208094f00)
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:107 +0x2e6
created by main.main
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:637 +0x1cd9

goroutine 19 [syscall]:
syscall.Syscall(0x0, 0xf, 0xc20944bee0, 0x10000, 0x414975, 0xc2093db5c0, 0xc2094636b0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xf, 0xc20944bee0, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0xf, 0xc20944bee0, 0x10000, 0x10000, 0xc20805e614, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc2083c29c0)
	/root/.go/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0x12c
created by github.com/howeyc/fsnotify.NewWatcher
	/root/.go/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x420

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2093f68b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2093f68b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2093f6850, 0x0, 0x7fce11a12f70, 0xc209404b48)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2081ffaf8, 0x6c8004, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2081ffaf8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2083c2a20, 0x7fce0ea0c400, 0xc2081ffaf8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2083c2a20, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc208074bc0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1808 +0xba
github.com/cgrates/cgrates/engine.(*Server).ServeHTTP(0x118b06a, 0xc208074bc0, 0xe)
	/root/.go/src/github.com/cgrates/cgrates/engine/server.go:113 +0x22c
main.serveHttp(0xc208038410, 0x1, 0x1)
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:380 +0xc2
created by main.main
	/root/.go/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:645 +0x1ae7

goroutine 20 [runnable]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc2083c29c0)
	/root/.go/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x55
created by github.com/howeyc/fsnotify.NewWatcher
	/root/.go/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x43a
```

**Comment by eloycoto** [comment]
Hi, 

I found the problem, I have 2 timings (offpeak and peak), when the call start on timming offpeak and finish in different timming (peak) the system raise this exception. 

If I add  the following line in engine/balances.go:422:
````
Logger.Crit(fmt.Sprintf("Rate Interval GETMAXCOST: %v", ts))
````
I got the following message: 

```
Apr 24 10:26:06 cgrates-prod CGRateS[2905]: Rate Interval GETMAXCOST: &{2015-04-24 07:59:04 +0000 UTC 2015-04-24 08:00
:00 +0000 UTC 0 0xc2099ee200 <nil> 56s [] *out:foehn:postpaid:foehn 0034678 SPN_MOB}
```
In this case, getMaxcost return 0.0, ""
https://github.com/cgrates/cgrates/blob/master/engine/rateinterval.go#L348

Any idea?
Thanks ;-)

**Comment by eloycoto** [comment]
Hi, 

I've just make more test, and the issue is that ts.Rateinterval is nil, so raise a new exception. 

https://github.com/cgrates/cgrates/blob/master/engine/balances.go#L423

Regards,

**Comment by rif** [comment]
One more debug please: before the line please print cd.RatingInfos
I suspect something miss-configured there.

**Comment by eloycoto** [comment]
Hi @rif, 

Here you have the debug of the ratingInfos: 

```
pr 27 09:39:14 cgrates-prod CGRateS[23839]: CD: &{Direction:*out Category:postpaid Tenant:foehn Subject:foehn Account:foehn Destination:0034678096720 TimeStart:2015-04-24 07:59:04 +0000 UTC TimeEnd:2015-04-24 08:02:00 +0000 UTC LoopIndex:0 DurationIndex:2m56s FallbackSubject: RatingInfos:[0xc2094a9480] Increments:[] TOR:*voice MaxRate:0 MaxRateUnit:0 MaxCostSoFar:0 account:0xc2094a4af0 test_callcost:<nil>}
Apr 27 09:39:14 cgrates-prod CGRateS[23839]: CC: &{Direction:*out Category:postpaid Tenant:foehn Subject:foehn Account:foehn Destination:0034678096720 TOR:*voice Cost:0.52266 Timespans:[0xc2094c65a0 0xc2094c6640] deductConnectFee:true maxCostDisconect:false}
Apr 27 09:39:14 cgrates-prod CGRateS[23839]: TS: &{TimeStart:2015-04-24 07:59:04 +0000 UTC TimeEnd:2015-04-24 08:00:00 +0000 UTC Cost:0 ratingInfo:0xc2094a9480 RateInterval:<nil> DurationIndex:56s Increments:[] MatchedSubject:*out:foehn:postpaid:foehn MatchedPrefix:0034678 MatchedDestId:SPN_MOB}
Apr 27 09:39:14 cgrates-prod CGRateS[23839]: BAL: &{Uuid:166dbd234078ab528070d23bbf9a567d Id: Value:1502.6065879934 ExpirationDate:0001-01-01 00:00:00 +0000 UTC Weight:10 DestinationId:*any RatingSubject: Category: SharedGroup: Timings:[] TimingIDs: precision:0 account:0xc2094a4af0 dirty:false}
Apr 27 09:39:14 cgrates-prod CGRateS[23839]: RatingInfos: [0xc2094a9480]
```

Regards

**Comment by rif** [comment]
pushed a fix for this issue. Please test again with latest version.
