### ISSUE TITLE
cgr-engine crashed after changes of csv files

### ISSUE THREAD

**Issue by mfrlinux** [cgrates/cgrates#648]
- CGRateS 0.9.1~rc8
-  OpenSIPS (2.2.2 (x86_64/linux))
- CentOS Linux release 7.3.1611 kernel 3.10.0-229.1.2.el7.x86_64
- Scenario: Changes made to the csv files - Timings, Rates and Destinations. The cgr-engine crashed! Even returning to the original csv files, the cgr-engine continues to fall. I noticed that the processing and memory usage of the cgr-engine PID started at high values.
- Backtrace
```
panic: runtime error: index out of range

goroutine 49 [running]:
panic(0xdb4bc0, 0xc42000c100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cgrates/cgrates/engine.(*RITiming).getLeftMargin(0xc420188460, 0xed058735d, 0xc4319fa023, 0x141d980, 0x1359460, 0xc4233950e0, 0x0)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/rateinterval.go:146 +0x268
github.com/cgrates/cgrates/engine.(*RITiming).IsActiveAt(0xc420188460, 0xed058735d, 0x319fa023, 0x141d980, 0xc4233950e0)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/rateinterval.go:175 +0x7f
github.com/cgrates/cgrates/engine.(*RateInterval).Contains(0xc4203fa6e0, 0xed058735d, 0x319fa023, 0x141d980, 0x647f00, 0xed0587399)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/rateinterval.go:295 +0x57
github.com/cgrates/cgrates/engine.RatingInfo.SelectRatingIntevalsForTimespan(0xc423395080, 0x24, 0xc420433b00, 0xa, 0xc4233d1214, 0x4, 0xc4233d1936, 0x6, 0xeca667500, 0x0, ...)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/ratingprofile.go:100 +0x13b
github.com/cgrates/cgrates/engine.(*CallDescriptor).splitInTimeSpans(0xc420075760, 0x0, 0x0, 0xed058735d)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/calldesc.go:397 +0x2e9
github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc420075760, 0xc4233d1c30, 0x1, 0x1)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/calldesc.go:536 +0x111
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetCost(0xc420075760, 0xc4203fa600, 0x12, 0x0)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/calldesc.go:468 +0x4b
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetLCR(0xc4200751e0, 0x1352ae0, 0xc4202ff5c0, 0x0, 0x0, 0x1352560, 0xc42000d730, 0xed1f09)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/calldesc.go:980 +0x4f7b
github.com/cgrates/cgrates/engine.(*Responder).GetLCR(0xc4201d3f90, 0xc4221b3938, 0xc4221b3950, 0xc4200751e0, 0x0)
	/root/projects/src/src/github.com/cgrates/cgrates/engine/responder.go:562 +0x316
github.com/cgrates/cgrates/apier/v1.(*ApierV1).GetLcrSuppliers(0xc4202ee000, 0xed1af5, 0x4, 0xc420127f50, 0xb, 0xc420127e98, 0x4, 0xc4233d1210, 0x4, 0xc4233d1210, ...)
	/root/projects/src/src/github.com/cgrates/cgrates/apier/v1/lcr.go:67 +0x109
reflect.Value.call(0xc4202137a0, 0xc420026ed8, 0x13, 0xed1df9, 0x4, 0xc4221b3ed0, 0x3, 0x3, 0x14231d0, 0x7fe7bd2bcc80, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc4202137a0, 0xc420026ed8, 0x13, 0xc4221b3ed0, 0x3, 0x3, 0x7fe7bd2bcc80, 0x0, 0x76cff1e6)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc4201c32c0, 0xc420019740, 0xc4233d0f90, 0xc422285b00, 0xc420402300, 0xea5ac0, 0xc420175e00, 0x199, 0xd4c1a0, 0xc4233d1220, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x148
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x421
```

**Comment by danbogos** [comment]
hi @mfrlinux 
Can u share also the .csv file which has created the crash? Most probably you have configured something wrong inside, however we will fix the crash as soon as we find the source.

Thanks,
DanB

**Comment by mfrlinux** [comment]
Thanks DanB.
I added all the csv files - (https://github.com/mfrlinux/TariffPlan)
The files have been edited via example cgrates/data/tariffplans/tutorial, when I go back to the original files it continues crashing.

**Comment by danbogos** [comment]
Hi

I see you have no default rates. Your starts only from 07:30 (PEAK). This means the engine does not find anything for before 07:30 (and maybe also during weekend). Also in RatingProfiles.csv you have defined 2 lines however they will overwrite each other, so you will end up with only one loaded.
Can u correct that (especially default rating) and retest (easiest is to put *any as Timing in RatingPlans.csv).

DanB

**Comment by mfrlinux** [comment]
changes done but any change causes crash

**Comment by danbogos** [comment]
hey @mfrlinux,

Sorry, I got my attention diverted from this issue. Can you please contact me on IRC so we can see how far you got?
Normally you should be able to fix your RatingPlan by overloading with a corrected version of rates.csv.

DanB

**Comment by mfrlinux** [comment]
Removed RatingPlan via Redis that was causing a problem.
