### ISSUE TITLE
ExportTPToFolder API Issue

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#739]
Hello Dear CGRateS Team!
I was trying to use ApierV2.ExportTPToFolder method but with no luck.
Whatever parameters I tried, the response is error": "SERVER_ERROR: NOT_FOUND".
Empty tpexport.zip file is created when compression=true.
And when "TPid" is missing, it crashes CGRateS with the following 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xceacf7]

goroutine 98 [running]:
github.com/cgrates/cgrates/apier/v2.(*ApierV2).ExportTPToFolder(0xc420362f80, 0x0, 0x0, 0x0, 0xc420123c60, 0xc420123c70, 0xc42036e4b0, 0x0, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v2/tp.go:44 +0x37
reflect.Value.call(0xc42006ca80, 0xc42000f2b0, 0x13, 0xf8b040, 0x4, 0xc4204e5f20, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc42006ca80, 0xc42000f2b0, 0x13, 0xc4204ca720, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420423f00, 0xc420118000, 0xc420123b40, 0xc42014a980, 0xc420492600, 0xedbba0, 0xc42036e420, 0x199, 0xdc0f00, 0xc42036e4b0, ...)
        /usr/local/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:481 +0x404 
```

Thanks,
Michael

**Comment by danbogos** [comment]
Hey Michael,

Can you please send us a capture with ngrep of your API call?

Thanks,
DanB

**Comment by muxalko** [comment]
Yeah,

Here is what I do :
```
#
T 2017/09/15 17:04:22.498456 10.192.210.110:50799 -> 10.224.228.186:2080 [AP]
POST /jsonrpc HTTP/1.1.
Host: 10.224.228.186:2080.
Connection: keep-alive.
Content-Length: 161.
Origin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm.
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36.
Content-Type: application/json.
Accept: */*.
Accept-Encoding: gzip, deflate.
Accept-Language: en-US,en;q=0.8,und;q=0.6.
Cookie: sessionid=2cf6aec3401ba7c48051c4387ac50fc9.
.
{
  "method":"ApierV2.ExportTPToFolder",
  "params":[
  {
    "TPid":"GTP",      
.
."ExportPath":"/home/golan/tariff_golan/",
."Compress": true
  }
],
"id":0
}

##
T 2017/09/15 17:04:22.500904 10.224.228.186:2080 -> 10.192.210.110:50799 [AP]
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Fri, 15 Sep 2017 14:04:22 GMT.
Content-Length: 57.
.
{"id":0,"result":null,"error":"SERVER_ERROR: NOT_FOUND"}

#
T 2017/09/15 17:04:22.702165 10.224.228.186:2080 -> 10.192.210.110:50799 [AP]
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Fri, 15 Sep 2017 14:04:22 GMT.
Content-Length: 57.
.
{"id":0,"result":null,"error":"SERVER_ERROR: NOT_FOUND"}

#
T 2017/09/15 17:04:22.704660 10.192.210.110:50799 -> 10.224.228.186:2080 [A]
......
```

And this one for crash
```
##
T 2017/09/15 17:04:33.315726 10.192.210.110:50799 -> 10.224.228.186:2080 [AP]
POST /jsonrpc HTTP/1.1.
Host: 10.224.228.186:2080.
Connection: keep-alive.
Content-Length: 136.
Origin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm.
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36.
Content-Type: application/json.
Accept: */*.
Accept-Encoding: gzip, deflate.
Accept-Language: en-US,en;q=0.8,und;q=0.6.
Cookie: sessionid=2cf6aec3401ba7c48051c4387ac50fc9.
.
{
  "method":"ApierV2.ExportTPToFolder",
  "params":[
  {

."ExportPath":"/home/golan/tariff_golan/",
."Compress": true
  }
],
"id":0
}

##
T 2017/09/15 17:04:33.337345 10.192.210.110:50799 -> 10.224.228.186:2080 [A]
......
#
T 2017/09/15 17:04:33.337436 10.192.210.110:50799 -> 10.224.228.186:2080 [AF]
......
############
```

**Comment by TeoV** [comment]
Hey Michael,

We fix the crush, but about the "SERVER_ERROR: NOT_FOUND" will continue investigating

**Comment by muxalko** [comment]
Hello TeoV,
Were you be able to reproduce the  "SERVER_ERROR: NOT_FOUND" at your end ?
I am using MongoDB.

**Comment by TeoV** [comment]
Hey Michael,
I want to apologize because I didn't answer to you but I was very busy the whole weekend plus that it was a storm in my town and didn't have internet until now. Tomorrow I will try and will come back with an answer.

**Comment by TeoV** [comment]
Hey Michael,

Now the method should work. If you can test it and come back with a result.
