### ISSUE TITLE
Loader dry_run crashing on broken references

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#83]
cgr-loader -dry_run
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x505b53]

goroutine 1 [running]:
github.com/cgrates/cgrates/engine.(*TpReader).LoadRatingProfiles(0xc2080771d0, 0x0, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/tp_reader.go:312 +0x8f3
github.com/cgrates/cgrates/engine.(*TpReader).LoadAll(0xc2080771d0, 0x0, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/tp_reader.go:898 +0x15f
main.main()
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-loader/cgr-loader.go:160 +0xded

**Comment by danbogos** [comment]
Implemented in master.
