### ISSUE TITLE
cgrates crashes after upgrade 

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#937]
Hi 

I've upgraded to the latest master (commit 465f06)

On the freeswitch host I have cgrates with Sessions and freeswitch_agent components enabled only.

cgrates crashes with the following errors in console:

```
root@VM-0-7-debian:/etc/cgrates# cgr-engine
2018/02/01 21:37:04 method Call has wrong number of ins: 4
2018/02/01 21:37:04 method Call has wrong number of ins: 4
2018/02/01 21:37:04 method BiRPCV1GetActiveSessions has wrong number of ins: 4
2018/02/01 21:37:04 method BiRPCV1GetPassiveSessions has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcAuthorizeEvent has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcAuthorizeEventWithDigest has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcInitiateSession has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcProcessCDR has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcProcessEvent has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcTerminateSession has wrong number of ins: 4
2018/02/01 21:37:04 method BiRpcUpdateSession has wrong number of ins: 4
2018/02/01 21:37:04 method Handlers has wrong number of ins: 1

panic: reflect: Call using *engine.CDR as type utils.CGREvent

goroutine 43 [running]:
reflect.Value.call(0xf95f60, 0xc42009e000, 0x5213, 0xfa4ab7, 0x4, 0xc42044bda0, 0x3, 0x3, 0xc42000f1b8, 0xde7b40, ...)
        /usr/local/go/src/reflect/value.go:371 +0x1290
reflect.Value.Call(0xf95f60, 0xc42009e000, 0x5213, 0xc42044bda0, 0x3, 0x3, 0xc42009e000, 0x5213, 0x11)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/sessions.(*SMGeneric).CallBiRPC(0xc42009e000, 0x14e0a00, 0xc4203a21b0, 0xfb6125, 0x15, 0xf92da0, 0xc42023d7c0, 0xde7b40, 0xc4201d6610, 0x0, ...)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/sessions/sessions.go:1023 +0x348
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/utils.(*BiRPCInternalClient).Call(0xc420286980, 0xfb6125, 0x15, 0xf92da0, 0xc42023d7c0, 0xde7b40, 0xc4201d6610, 0x0, 0x0)  
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/utils/birpcint_client.go:66 +0x91
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents.(*FSsessions).onChannelHangupComplete(0xc4203a21b0, 0xc4204e1050, 0xc42042f830, 0x24)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents/fsagent.go:239 +0x1f7
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents.(*FSsessions).createHandlers.func2(0xc42042a000, 0x3d85, 0xc42042f830, 0x24)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents/fsagent.go:61 +0x6a
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/fsock.(*FSock).dispatchEvent
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/fsock/fsock.go:388 +0x209
```

This happens only if I have:

"create_cdr": true,

in "freeswitch_agent" component.
If I set it to false, cgrates doesn't crash, but doesn't produce and store CDR to the storeDB.

Thank you.
Arsen.

**Comment by danbogos** [comment]
Hi @arsperger 

@TeoV has pushed a fix. Please test and let us know if issue fixed.

Ta,
DanB

**Comment by arsperger** [comment]
Hi Dan,

The issue is still there:

```
panic: reflect: Call using *utils.CGREvent as type utils.CGREvent

goroutine 43 [running]:
reflect.Value.call(0xf95f60, 0xc42009e000, 0x5213, 0xfa4ab7, 0x4, 0xc420449da0, 0x3, 0x3, 0xc42000fbb0, 0xde7b40, ...)
        /usr/local/go/src/reflect/value.go:371 +0x1290
reflect.Value.Call(0xf95f60, 0xc42009e000, 0x5213, 0xc420449da0, 0x3, 0x3, 0xc42009e000, 0x5213, 0x11)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/sessions.(*SMGeneric).CallBiRPC(0xc42009e000, 0x14e0a00, 0xc42035e1b0, 0xfb6125, 0x15, 0xee8a00, 0xc4202fc380, 0xde7b40, 0xc420158450, 0xc4202fc380, ...)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/sessions/sessions.go:1023 +0x348
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/utils.(*BiRPCInternalClient).Call(0xc420286a00, 0xfb6125, 0x15, 0xee8a00, 0xc4202fc380, 0xde7b40, 0xc420158450, 0x0, 0x0)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/utils/birpcint_client.go:66 +0x91
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents.(*FSsessions).onChannelHangupComplete(0xc42035e1b0, 0xc4201e53e0, 0xc42042f860, 0x24)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents/fsagent.go:239 +0x205
github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents.(*FSsessions).createHandlers.func2(0xc420440000, 0x3e43, 0xc42042f860, 0x24)
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/cgrates/agents/fsagent.go:61 +0x6a
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/fsock.(*FSock).dispatchEvent
        /root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/fsock/fsock.go:388 +0x209
```

Thanks.
Arsen.

**Comment by danbogos** [comment]
Hey @arsperger

Can you give another try pls?

DanB

**Comment by arsperger** [comment]
Hi Dan,

It is working now. Thanks

**Comment by danbogos** [comment]
Great, thanks for reporting!
