### ISSUE TITLE
Issue trying to remove AccountActionTriggers

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#99]
Hello,

I am trying to remove a number of AccountActionTriggers

 from an account and the API calls are causing cgrates to crash.  The additional ones (7 in total) got created because I was trying to correct the first one that had a typo and I recreated the AccountActionTriggers without first removing the existing one. 

I am trying to remove all of them using the API call from the command line:
curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.RemAccountActionTriggers","params":[{"Tenant":"cgrates.org","Account":"322181565","Direction":"*out","ActionTriggersId":"BALANCE_ALERT"}]}' http://localhost:2080/jsonrpc

but instead I get this response: curl: (52) Empty reply from server.  See the attached strace below.

## AccountActionTriggers
````
{
  "id": null,
  "result": [
    {
      "Id": "BALANCE_ALERT",
      "ThresholdType": "*min_balance",
      "ThresholdValue": 25,
      "Recurrent": false,
      "MinSleep": 0,
      "BalanceId": "",
      "BalanceType": "*monetary",
      "BalanceDirection": "*out",
      "BalanceDestinationIds": "",
      "BalanceWeight": 0,
      "BalanceExpirationDate": "0001-01-01T00:00:00Z",
      "BalanceTimingTags": "",
      "BalanceRatingSubject": "",
      "BalanceCategory": "",
      "BalanceSharedGroup": "",
      "Weight": 10,
      "ActionsId": "BALANCE_ALTERT",
      "MinQueuedItems": 0,
      "Executed": false
    },
    {
      "Id": "BALANCE_ALERT",
      "ThresholdType": "*min_balance",
      "ThresholdValue": 25,
      "Recurrent": false,
      "MinSleep": 0,
      "BalanceId": "",
      "BalanceType": "*monetary",
      "BalanceDirection": "*out",
      "BalanceDestinationIds": "",
      "BalanceWeight": 0,
      "BalanceExpirationDate": "0001-01-01T00:00:00Z",
      "BalanceTimingTags": "",
      "BalanceRatingSubject": "",
      "BalanceCategory": "",
      "BalanceSharedGroup": "",
      "Weight": 10,
      "ActionsId": "BALANCE_ALERT",
      "MinQueuedItems": 0,
      "Executed": false
    },
    <<Snipped>>

    {
      "Id": "BALANCE_ALERT",
      "ThresholdType": "*min_balance",
      "ThresholdValue": 30,
      "Recurrent": false,
      "MinSleep": 0,
      "BalanceId": "",
      "BalanceType": "*monetary",
      "BalanceDirection": "*out",
      "BalanceDestinationIds": "",
      "BalanceWeight": 0,
      "BalanceExpirationDate": "0001-01-01T00:00:00Z",
      "BalanceTimingTags": "",
      "BalanceRatingSubject": "",
      "BalanceCategory": "",
      "BalanceSharedGroup": "",
      "Weight": 10,
      "ActionsId": "BALANCE_ALERT",
      "MinQueuedItems": 0,
      "Executed": true
    }
  ],
  "error": null
}
```
## cgrates.strace

````
### Started at: Thu Jun 18 12:08:25 UTC 2015
panic: runtime error: index out of range

goroutine 37 [running]:
github.com/cgrates/cgrates/apier/v1.func·002(0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/accounts.go:143 +0x425
github.com/cgrates/cgrates/engine.(*AccountLock).Guard(0x11d1550, 0xc2089f7a00, 0xc2089f79c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/accountlock.go:44 +0x219
github.com/cgrates/cgrates/apier/v1.(*ApierV1).RemAccountActionTriggers(0xc20812c1c0, 0xc2085ec300, 0x14, 0xc2086d4290, 0x9, 0xc2086d429c, 0x4, 0xc2086d42b0, 0xd, 0xc2086d42c0, ...)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/accounts.go:152 +0x29b
reflect.Value.call(0xb7e5e0, 0xd24ed0, 0x13, 0xd4b070, 0x4, 0xc2089f7f28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xb7e5e0, 0xd24ed0, 0x13, 0xc2089f7f28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc208102180, 0xc208035640, 0xc2086d41d0, 0xc2080ab580, 0xc2085ec440, 0xc80420, 0xc208102440, 0xd9, 0xa80b20, 0xc2086d42c0, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:476 +0x44a

goroutine 1 [chan receive, 7 minutes]:
main.main()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:628 +0x1b10

goroutine 5 [syscall, 7 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan send, 7 minutes]:
github.com/cgrates/cgrates/balancer2go.func·001()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/balancer2go/balancer.go:31 +0x15f
created by github.com/cgrates/cgrates/balancer2go.NewBalancer
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/balancer2go/balancer.go:34 +0x15b

goroutine 8 [chan receive, 7 minutes]:
database/sql.(*DB).connectionOpener(0xc208126140)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 11 [IO wait, 5 minutes]:
net.(*pollDesc).Wait(0xc208010300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080102a0, 0x0, 0x7f1ec45c5f70, 0xc2082a8338)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2086aa048, 0x6, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2086aa048, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/cgrates/cgrates/engine.(*Server).ServeGOB(0x11dd16c, 0xc2080d6aa0, 0xe)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/server.go:85 +0x326
created by main.serveRpc
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:373 +0x108

goroutine 9 [chan receive, 7 minutes]:
main.generalSignalHandler()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:49 +0x25b
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:559 +0x12b4

goroutine 18 [chan receive, 7 minutes]:
github.com/cgrates/cgrates/scheduler.(*Scheduler).Loop(0xc208144180)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/scheduler/scheduler.go:45 +0x61
main.func·001()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:570 +0x154
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:571 +0x13c4

goroutine 10 [IO wait, 5 minutes]:
net.(*pollDesc).Wait(0xc208010290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010230, 0x0, 0x7f1ec45c5f70, 0xc2082a8258)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2086aa038, 0x6, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2086aa038, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/cgrates/cgrates/engine.(*Server).ServeJSON(0x11dd16c, 0xc2080d6a80, 0xe)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/server.go:63 +0x326
created by main.serveRpc
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:372 +0xcc

goroutine 20 [chan receive, 5 minutes]:
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect(0xc2080a4500, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:93 +0xa11
main.startSmFreeSWITCH(0xc2081440f0, 0x7f1ec45c95c0, 0xc20812e008, 0xc2080580c0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:155 +0x672
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:596 +0x17ad

goroutine 21 [chan receive, 7 minutes]:
main.shutdownSessionmanagerSingnalHandler()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:126 +0x2b3
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:598 +0x17be

goroutine 23 [IO wait]:
net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080101c0, 0x0, 0x7f1ec45c5f70, 0xc2086d4088)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2086aa028, 0x6bf59e, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2086aa028, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208e406c0, 0x7f1ec1539178, 0xc2086aa028, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208e406c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc2080d6ac0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1808 +0xba
github.com/cgrates/cgrates/engine.(*Server).ServeHTTP(0x11dd16c, 0xc2080d6ac0, 0xe)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/server.go:113 +0x22c
main.serveHttp(0xc20812e048, 0x1, 0x1)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:381 +0xc2
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:627 +0x1ae9

goroutine 24 [chan receive, 7 minutes]:
main.reloadSchedulerSingnalHandler(0xc208144180, 0x7f1ec45c8ef0, 0xc20809b3a0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:111 +0x172
created by main.func·001
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:566 +0xd7

goroutine 25 [IO wait, 5 minutes]:
net.(*pollDesc).Wait(0xc20812cc30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20812cc30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20812cbd0, 0xc2089f2000, 0x2000, 0x2000, 0x0, 0x7f1ec45c5f70, 0xc2086d4238)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2088e8070, 0xc2089f2000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc208d1ac60)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208d1ac60, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadBytes(0xc208d1ac60, 0x42480a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:374 +0xd2
github.com/cgrates/fsock.(*FSock).readHeaders(0xc208128500, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:224 +0xea
github.com/cgrates/fsock.(*FSock).readEvent(0xc208128500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:264 +0xb7
github.com/cgrates/fsock.(*FSock).readEvents(0xc208128500, 0xc208d1aea0, 0xc208d1af00)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:289 +0x6b
created by github.com/cgrates/fsock.(*FSock).Connect
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:471 +0x769

goroutine 26 [chan receive, 5 minutes]:
github.com/cgrates/fsock.(*FSock).ReadEvents(0xc208128500, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:556 +0x69
github.com/cgrates/cgrates/sessionmanager.func·001()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:71 +0x73
created by github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:74 +0x574

goroutine 27 [sleep]:
github.com/cgrates/cgrates/sessionmanager.func·002()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:86 +0x3e
created by github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:90 +0x9a8

goroutine 34 [IO wait]:
net.(*pollDesc).Wait(0xc20812cca0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20812cca0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20812cc40, 0xc2089f0000, 0x2000, 0x2000, 0x0, 0x7f1ec45c5f70, 0xc2086d4230)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2088ae000, 0xc2089f0000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc208d1b140)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208d1b140, 0xc2089f000a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadBytes(0xc208d1b140, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:374 +0xd2
github.com/cgrates/fsock.(*FSock).readHeaders(0xc208128640, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:224 +0xea
github.com/cgrates/fsock.(*FSock).readEvent(0xc208128640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:264 +0xb7
github.com/cgrates/fsock.(*FSock).readEvents(0xc208128640, 0xc208d1b1a0, 0xc208d1b200)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:289 +0x6b
created by github.com/cgrates/fsock.(*FSock).Connect
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/fsock/fsock.go:471 +0x769

goroutine 35 [chan receive]:
github.com/cgrates/cgrates/engine.(*rpcRequest).Call(0xc20857c1b0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/server.go:149 +0x98
github.com/cgrates/cgrates/engine.func·020(0x7f1ec1539280, 0xc208128820, 0xc208106000)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/server.go:101 +0x223
net/http.HandlerFunc.ServeHTTP(0xf4a238, 0x7f1ec1539280, 0xc208128820, 0xc208106000)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803aa50, 0x7f1ec1539280, 0xc208128820, 0xc208106000)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208e406c0, 0x7f1ec1539280, 0xc208128820, 0xc208106000)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208128780)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
````
Thanks

Errol

**Comment by ewsamuels** [comment]
Confirmed fixed.
